// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package codegenmanifest

type AliasStrategy string

const AliasStrategyBasename AliasStrategy = "basename"
const AliasStrategyInternalId AliasStrategy = "internal-id"
const AliasStrategyRelativePath AliasStrategy = "relative-path"
const AliasStrategySourceUri AliasStrategy = "source-uri"

// Language-agnostic manifest for pinned sources, prepared inputs, and generator
// products.
type CodegenManifest struct {
	// Defaults corresponds to the JSON schema field "defaults".
	Defaults *Defaults `json:"defaults,omitempty" yaml:"defaults,omitempty" mapstructure:"defaults,omitempty"`

	// Named generator profiles. Generators are tool-specific but source-agnostic.
	Generators GeneratorMap `json:"generators" yaml:"generators" mapstructure:"generators"`

	// Prepared logical inputs derived from one or more sources.
	Inputs InputMap `json:"inputs" yaml:"inputs" mapstructure:"inputs"`

	// Named products generated from configured inputs and generators.
	Products ProductMap `json:"products" yaml:"products" mapstructure:"products"`

	// Reusable schema registry profiles for JSON Schema-oriented inputs.
	RegistryProfiles RegistryProfileMap `json:"registry_profiles,omitempty" yaml:"registry_profiles,omitempty" mapstructure:"registry_profiles,omitempty"`

	// Named source definitions materialized locally before generators run.
	Sources SourceMap `json:"sources" yaml:"sources" mapstructure:"sources"`

	// Manifest format version.
	Version int `json:"version" yaml:"version" mapstructure:"version"`
}

type Defaults struct {
	// Fetch corresponds to the JSON schema field "fetch".
	Fetch *FetchDefaults `json:"fetch,omitempty" yaml:"fetch,omitempty" mapstructure:"fetch,omitempty"`

	// Generator corresponds to the JSON schema field "generator".
	Generator GeneratorDefaults `json:"generator,omitempty" yaml:"generator,omitempty" mapstructure:"generator,omitempty"`
}

type DirectorySource struct {
	// Description corresponds to the JSON schema field "description".
	Description *NonEmptyString `json:"description,omitempty" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// Format corresponds to the JSON schema field "format".
	Format SchemaFormat `json:"format" yaml:"format" mapstructure:"format"`

	// Include corresponds to the JSON schema field "include".
	Include []NonEmptyString `json:"include,omitempty" yaml:"include,omitempty" mapstructure:"include,omitempty"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Path corresponds to the JSON schema field "path".
	Path PathString `json:"path" yaml:"path" mapstructure:"path"`
}

type FetchDefaults struct {
	// CacheDir corresponds to the JSON schema field "cache_dir".
	CacheDir *PathString `json:"cache_dir,omitempty" yaml:"cache_dir,omitempty" mapstructure:"cache_dir,omitempty"`
}

type Generator struct {
	// Description corresponds to the JSON schema field "description".
	Description *NonEmptyString `json:"description,omitempty" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// Language corresponds to the JSON schema field "language".
	Language LanguageName `json:"language" yaml:"language" mapstructure:"language"`

	// Options corresponds to the JSON schema field "options".
	Options GeneratorOptions `json:"options,omitempty" yaml:"options,omitempty" mapstructure:"options,omitempty"`

	// Tool corresponds to the JSON schema field "tool".
	Tool NonEmptyString `json:"tool" yaml:"tool" mapstructure:"tool"`
}

// Tool-specific default generator options merged into individual generator
// profiles.
type GeneratorDefaults map[string]interface{}

// Named generator profiles. Generators are tool-specific but source-agnostic.
type GeneratorMap map[string]Generator

type GeneratorOptions map[string]interface{}

type GeneratorRefList []Identifier

type GitHubRawSource struct {
	// Description corresponds to the JSON schema field "description".
	Description *NonEmptyString `json:"description,omitempty" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// Format corresponds to the JSON schema field "format".
	Format SchemaFormat `json:"format" yaml:"format" mapstructure:"format"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Metadata corresponds to the JSON schema field "metadata".
	Metadata *GitHubRawSourceMetadata `json:"metadata,omitempty" yaml:"metadata,omitempty" mapstructure:"metadata,omitempty"`

	// Owner corresponds to the JSON schema field "owner".
	Owner Identifier `json:"owner" yaml:"owner" mapstructure:"owner"`

	// Path corresponds to the JSON schema field "path".
	Path PathString `json:"path" yaml:"path" mapstructure:"path"`

	// Pinned commit SHA, tag, or branch reference to fetch.
	Ref NonEmptyString `json:"ref" yaml:"ref" mapstructure:"ref"`

	// Repo corresponds to the JSON schema field "repo".
	Repo NonEmptyString `json:"repo" yaml:"repo" mapstructure:"repo"`
}

type GitHubRawSourceMetadata struct {
	// Package corresponds to the JSON schema field "package".
	Package *NonEmptyString `json:"package,omitempty" yaml:"package,omitempty" mapstructure:"package,omitempty"`

	// PackageVersion corresponds to the JSON schema field "package_version".
	PackageVersion *NonEmptyString `json:"package_version,omitempty" yaml:"package_version,omitempty" mapstructure:"package_version,omitempty"`

	// Tag corresponds to the JSON schema field "tag".
	Tag *NonEmptyString `json:"tag,omitempty" yaml:"tag,omitempty" mapstructure:"tag,omitempty"`
}

// Absolute HTTPS URL.
type HttpsUrl string

// Stable manifest identifier used as a map key.
type Identifier string

type Input interface{}

// Prepared logical inputs derived from one or more sources.
type InputMap map[string]Input

type InputRefList []Identifier

type JsonSchemaInput struct {
	// Description corresponds to the JSON schema field "description".
	Description *NonEmptyString `json:"description,omitempty" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// Entrypoints corresponds to the JSON schema field "entrypoints".
	Entrypoints []NonEmptyString `json:"entrypoints" yaml:"entrypoints" mapstructure:"entrypoints"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Prepare corresponds to the JSON schema field "prepare".
	Prepare *PrepareConfig `json:"prepare,omitempty" yaml:"prepare,omitempty" mapstructure:"prepare,omitempty"`

	// RegistryProfile corresponds to the JSON schema field "registry_profile".
	RegistryProfile *Identifier `json:"registry_profile,omitempty" yaml:"registry_profile,omitempty" mapstructure:"registry_profile,omitempty"`

	// Sources corresponds to the JSON schema field "sources".
	Sources SourceRefList `json:"sources" yaml:"sources" mapstructure:"sources"`
}

// Target language identifier such as python or go.
type LanguageName string

type NonEmptyString string

// Filesystem path expressed with POSIX separators.
type PathString string

type PrepareConfig struct {
	// Dereference corresponds to the JSON schema field "dereference".
	Dereference *PrepareConfigDereference `json:"dereference,omitempty" yaml:"dereference,omitempty" mapstructure:"dereference,omitempty"`

	// MergeRefSiblings corresponds to the JSON schema field "merge_ref_siblings".
	MergeRefSiblings *bool `json:"merge_ref_siblings,omitempty" yaml:"merge_ref_siblings,omitempty" mapstructure:"merge_ref_siblings,omitempty"`

	// SchemaTransforms corresponds to the JSON schema field "schema_transforms".
	SchemaTransforms []NonEmptyString `json:"schema_transforms,omitempty" yaml:"schema_transforms,omitempty" mapstructure:"schema_transforms,omitempty"`
}

type PrepareConfigDereference string

const PrepareConfigDereferenceInlineRefs PrepareConfigDereference = "inline-refs"
const PrepareConfigDereferenceNone PrepareConfigDereference = "none"

type Product struct {
	// Description corresponds to the JSON schema field "description".
	Description *NonEmptyString `json:"description,omitempty" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// Generators corresponds to the JSON schema field "generators".
	Generators GeneratorRefList `json:"generators" yaml:"generators" mapstructure:"generators"`

	// Inputs corresponds to the JSON schema field "inputs".
	Inputs InputRefList `json:"inputs" yaml:"inputs" mapstructure:"inputs"`

	// OutputTemplate corresponds to the JSON schema field "output_template".
	OutputTemplate NonEmptyString `json:"output_template" yaml:"output_template" mapstructure:"output_template"`
}

// Named products generated from configured inputs and generators.
type ProductMap map[string]Product

type RegistryConfig struct {
	// Crawl corresponds to the JSON schema field "crawl".
	Crawl *bool `json:"crawl,omitempty" yaml:"crawl,omitempty" mapstructure:"crawl,omitempty"`

	// Retrieve corresponds to the JSON schema field "retrieve".
	Retrieve *RetrieveConfig `json:"retrieve,omitempty" yaml:"retrieve,omitempty" mapstructure:"retrieve,omitempty"`
}

type RegistryProfile struct {
	// Aliases corresponds to the JSON schema field "aliases".
	Aliases []AliasStrategy `json:"aliases,omitempty" yaml:"aliases,omitempty" mapstructure:"aliases,omitempty"`

	// Registry corresponds to the JSON schema field "registry".
	Registry *RegistryConfig `json:"registry,omitempty" yaml:"registry,omitempty" mapstructure:"registry,omitempty"`

	// Resource corresponds to the JSON schema field "resource".
	Resource ResourceConfig `json:"resource" yaml:"resource" mapstructure:"resource"`
}

// Reusable schema registry profiles for JSON Schema-oriented inputs.
type RegistryProfileMap map[string]RegistryProfile

type ResourceConfig struct {
	// DefaultSpecification corresponds to the JSON schema field
	// "default_specification".
	DefaultSpecification *NonEmptyString `json:"default_specification,omitempty" yaml:"default_specification,omitempty" mapstructure:"default_specification,omitempty"`

	// Mode corresponds to the JSON schema field "mode".
	Mode ResourceConfigMode `json:"mode" yaml:"mode" mapstructure:"mode"`
}

type ResourceConfigMode string

const ResourceConfigModeFromContents ResourceConfigMode = "from-contents"

type RetrieveConfig struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind RetrieveConfigKind `json:"kind" yaml:"kind" mapstructure:"kind"`
}

type RetrieveConfigKind string

const RetrieveConfigKindNone RetrieveConfigKind = "none"

type SchemaFormat string

const SchemaFormatJson SchemaFormat = "json"
const SchemaFormatYaml SchemaFormat = "yaml"

type Source interface{}

// Named source definitions materialized locally before generators run.
type SourceMap map[string]Source

type SourceRefList []Identifier

type UrlSource struct {
	// Description corresponds to the JSON schema field "description".
	Description *NonEmptyString `json:"description,omitempty" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// Format corresponds to the JSON schema field "format".
	Format SchemaFormat `json:"format" yaml:"format" mapstructure:"format"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Uri corresponds to the JSON schema field "uri".
	Uri HttpsUrl `json:"uri" yaml:"uri" mapstructure:"uri"`
}

type WorkflowTemplateSchemaInput struct {
	// Description corresponds to the JSON schema field "description".
	Description *NonEmptyString `json:"description,omitempty" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Prepare corresponds to the JSON schema field "prepare".
	Prepare *PrepareConfig `json:"prepare,omitempty" yaml:"prepare,omitempty" mapstructure:"prepare,omitempty"`

	// Optional top-level definition name to treat as the logical entrypoint.
	Root *NonEmptyString `json:"root,omitempty" yaml:"root,omitempty" mapstructure:"root,omitempty"`

	// Sources corresponds to the JSON schema field "sources".
	Sources SourceRefList `json:"sources" yaml:"sources" mapstructure:"sources"`
}
