# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  lib,
  linkFarm,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig_0_15,
  name ? "zig-packages",
}:
let
  unpackZigArtifact =
    {
      name,
      artifact,
    }:
    runCommandLocal name
      {
        nativeBuildInputs = [ zig_0_15 ];
      }
      ''
        hash="$(zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
        mv "$TMPDIR/p/$hash" "$out"
        chmod 755 "$out"
      '';

  fetchZig =
    {
      name,
      url,
      hash,
    }:
    let
      artifact = fetchurl { inherit url hash; };
    in
    unpackZigArtifact { inherit name artifact; };

  fetchGitZig =
    {
      name,
      url,
      hash,
    }:
    let
      parts = lib.splitString "#" url;
      url_base = builtins.elemAt parts 0;
      url_without_query = builtins.elemAt (lib.splitString "?" url_base) 0;
      rev_base = builtins.elemAt parts 1;
      rev =
        if builtins.match "^[a-fA-F0-9]{40}$" rev_base != null then rev_base else "refs/heads/${rev_base}";
    in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
      fetchSubmodules = false;
    };

  fetchZigArtifact =
    {
      name,
      url,
      hash,
    }:
    let
      parts = lib.splitString "://" url;
      proto = builtins.elemAt parts 0;
      path = builtins.elemAt parts 1;
      fetcher = {
        "git+http" = fetchGitZig {
          inherit name hash;
          url = "http://${path}";
        };
        "git+https" = fetchGitZig {
          inherit name hash;
          url = "https://${path}";
        };
        http = fetchZig {
          inherit name hash;
          url = "http://${path}";
        };
        https = fetchZig {
          inherit name hash;
          url = "https://${path}";
        };
      };
    in
    fetcher.${proto};
in
linkFarm name [
  {
    name = "cli-0.10.0-2eKe_5kEAQBeHqKxUHNTGnETzu81rqKWwT1WPt1jXBt0";
    path = fetchZigArtifact {
      name = "cli";
      url = "https://github.com/sam701/zig-cli/archive/cb44aade25a3c1eddd8b6f990b50c2189442c1e2.tar.gz";
      hash = "sha256-kLSxN4QeRDRhsAZiGztMo+/k3O17fq3G9F+vIuSnTmg=";
    };
  }
  {
    name = "flags-0.11.0-a_9h3gR2AACtwEzEcKhIsYPEgNPbBeGYKhbYL4lsmJ1N";
    path = fetchZigArtifact {
      name = "flags";
      url = "https://github.com/JacobCrabill/zig-flags/archive/8f65f0d5bf0d92b950ddf16afb34533491831c7d.tar.gz";
      hash = "sha256-+e6muGCn58alIbAcX5H9BREfohBFVtevFdHAyAVaUyw=";
    };
  }
  {
    name = "humanize-0.0.5-xH2j9oHcAABixEpQnxZAi_btBp70H8-8OwkuUVM_XJ4e";
    path = fetchZigArtifact {
      name = "humanize";
      url = "git+https://github.com/burdzwastaken/zig-humanize#bf713d8165f5fce4db01af5e680d21fc31b074b5";
      hash = "sha256-NX43JsRAObauZpGVzpRaZaDZwhKoQ2DN+Cwdymz7yog=";
    };
  }
  {
    name = "kewpie-0.1.0-PG0ir0IzAABsQr2dPBazNu4Okyt7MX2b2cjbVGP76NkH";
    path = fetchZigArtifact {
      name = "kewpie";
      url = "git+https://github.com/weskoerber/kewpie#001fe8addccbf3ce171b31c6281cf82f2c487356";
      hash = "sha256-PYkKA9HYx9BH7Dzzds8KKP+PjxElw/shOHSXeRpfCFg=";
    };
  }
  {
    name = "known_folders-0.0.0-Fy-PJtTTAADUOhGKM0sxzG4eMkNQxRvx9e5dfHVyaeA3";
    path = fetchZigArtifact {
      name = "known_folders";
      url = "git+https://github.com/ziglibs/known-folders.git#ab5cf5feb936fa3b72c95d3ad0c0c67791937ba1";
      hash = "sha256-Pdn/nUclhHBB1COTzNNR5ysE13h6uLOFJjuFrasv/2I=";
    };
  }
  {
    name = "N-V-__8AABAhDAAIlXL7OA-0Z5sWQh_FOFGoImvOvJzkRGOg";
    path = fetchZigArtifact {
      name = "lua51";
      url = "https://www.lua.org/ftp/lua-5.1.5.tar.gz";
      hash = "sha256-JkD8VqeV8p0o7xXhPDSkfiI5YLAkDoywqC2bBzhpUzM=";
    };
  }
  {
    name = "N-V-__8AALg2DgDVsrOXOPBkTZ7Vt0MZc_Gha5N--G1M-FiH";
    path = fetchZigArtifact {
      name = "lua52";
      url = "https://www.lua.org/ftp/lua-5.2.4.tar.gz";
      hash = "sha256-ueLkqtZ4mztjoFbUQveznw7Pyjrg8fwK5OlhRAG2n0s=";
    };
  }
  {
    name = "N-V-__8AALihEACTeiI1Me9rP-qPZT3BNTELDoSAXn76FIhw";
    path = fetchZigArtifact {
      name = "lua53";
      url = "https://www.lua.org/ftp/lua-5.3.6.tar.gz";
      hash = "sha256-/F/Wm7hzYyPwJmcrG3I12mE9cXfnJViJOgvc0yBGbWA=";
    };
  }
  {
    name = "N-V-__8AAIMvFABt-Qcpk24RD10ldEN743D8Q2e19Er8x3dJ";
    path = fetchZigArtifact {
      name = "lua54";
      url = "https://www.lua.org/ftp/lua-5.4.7.tar.gz";
      hash = "sha256-n79eKO+GxphY9tPTTszDLpEcGii0Eg/z6EqqcM+/HjA=";
    };
  }
  {
    name = "N-V-__8AACcgQgCuLYTPzCp6pnBmFJHyG77RAtM13hjOfTaG";
    path = fetchZigArtifact {
      name = "luajit";
      url = "https://github.com/LuaJIT/LuaJIT/archive/c525bcb9024510cad9e170e12b6209aedb330f83.tar.gz";
      hash = "sha256-6yCv/HCp6XqKDh4LEEVvIg/KdjehmOSpN7X8gn3R75U=";
    };
  }
  {
    name = "N-V-__8AAFB1kwDHb7dLmDsOv91rOkqorfDB_2nJtqnp4F-b";
    path = fetchZigArtifact {
      name = "luau";
      url = "https://github.com/luau-lang/luau/archive/refs/tags/0.653.tar.gz";
      hash = "sha256-UuOmkOKgB0gwsP+CjUQqpihimad8c4cDwn8gVz7mxl8=";
    };
  }
  {
    name = "plutosvg-0.0.6-1-LyMxgYguAABq-4Xf7BWKdsl27x3fq5EUgsYS1LmGq9bW";
    path = fetchZigArtifact {
      name = "plutosvg";
      url = "https://github.com/JacobCrabill/zig-plutosvg/archive/b2dcac090852c9b26f16798dbbb35c3da1f65773.tar.gz";
      hash = "sha256-4+xEWdI6CPn8/rSCOPXERc/ECA+lXl1rrljVstikXtk=";
    };
  }
  {
    name = "N-V-__8AAE23BABBp4a-9A49LViXGvy9XpI_thZU1Rfwg9pl";
    path = fetchZigArtifact {
      name = "plutosvg";
      url = "https://github.com/sammycage/plutosvg/archive/9c3d6d701e3957a6bc61251f45852bfdf9cde3e9.tar.gz";
      hash = "sha256-y/KZ9eymJZ3si/hOODT8PvyTKwlNjfQoshlQ0hsVc+U=";
    };
  }
  {
    name = "N-V-__8AABt5DwAlC69cGd2MBdqvlbvpWTC0yDIsbgha3g9Y";
    path = fetchZigArtifact {
      name = "plutovg";
      url = "https://github.com/sammycage/plutovg/archive/refs/tags/v1.0.0.tar.gz";
      hash = "sha256-1KgBWu6e78KbAebav9PUs3GuEvnV6b4JeY3rd6Uop5Q=";
    };
  }
  {
    name = "zig_stb_image-2.28.0-2-9dD1dfoYBQCzF7IA9_-tSbsF1PgN7HGfzDzGVRG2BoUY";
    path = fetchZigArtifact {
      name = "stbi";
      url = "https://github.com/JacobCrabill/zig-stb-image/archive/db40631ef191d3692a706b142f524022c6be80d7.tar.gz";
      hash = "sha256-bMs+PCFSK683YHKlgz5+eiIEYr1DfmWLI9rJ/GGHbLw=";
    };
  }
  {
    name = "tree_sitter-0.26.0-1-Tw2sR8G6CwC1KrLeOIcy0vIjmiYYa2OkZzZ-ZV6QPVbg";
    path = fetchZigArtifact {
      name = "tree_sitter";
      url = "https://github.com/JacobCrabill/tree-sitter/archive/168ffad245131be4382c0f20938fd54a548feddd.tar.gz";
      hash = "sha256-AFiyl0lbjVcIzJtZhsyX8q/cudOzPrtUXaL3wu1dvUc=";
    };
  }
  {
    name = "N-V-__8AAG_cogDl9X3jxLCGR6dsBzkjlX8TYhtdCCvonOUr";
    path = fetchZigArtifact {
      name = "tree_sitter_bash";
      url = "https://github.com/tree-sitter/tree-sitter-bash/archive/49c31006d8307dcb12bc5770f35b6d5b9e2be68e.tar.gz";
      hash = "sha256-MwNk0TdqMqcUZFdONZim2yUZNblcaZSF9Rg1+LRCofM=";
    };
  }
  {
    name = "N-V-__8AALWcSAD2F6Vd1LSqa0js-e6kawfanpXMUnMhQeq6";
    path = fetchZigArtifact {
      name = "tree_sitter_c";
      url = "https://github.com/tree-sitter/tree-sitter-c/archive/e8841a6a9431b7365ac9055688429e1deb8db90f.tar.gz";
      hash = "sha256-4HQmlOz0GVqWH0Ho5IrTgOckHiVGrNP0TB1pe5qbT5o=";
    };
  }
  {
    name = "N-V-__8AACLOCQCV8GF5uI_qg4S3tygmCZMpxB9qk4L2evjb";
    path = fetchZigArtifact {
      name = "tree_sitter_cmake";
      url = "https://github.com/uyha/tree-sitter-cmake/archive/fe48221d4d9842d916d66b5e71ab3c6307ec28b3.tar.gz";
      hash = "sha256-Fh6rzNxxPauVwYLzeF0KTg+s1La5tOjLEJz2prTSlF0=";
    };
  }
  {
    name = "N-V-__8AABV0FwF4Ttn0MFCCLOxdUUKUC07SL-wqYa-2ySus";
    path = fetchZigArtifact {
      name = "tree_sitter_cpp";
      url = "https://github.com/tree-sitter/tree-sitter-cpp/archive/f41b4f66a42100be405f96bdc4ebc4a61095d3e8.tar.gz";
      hash = "sha256-+YUH//H+skIC2EH8L+OJv5Go6a7l+5/N52oy5o+LWQ8=";
    };
  }
  {
    name = "N-V-__8AACVXAgCEl--zqcqoXlvXpEMk5BTS748bsLVslERc";
    path = fetchZigArtifact {
      name = "tree_sitter_json";
      url = "https://github.com/tree-sitter/tree-sitter-json/archive/4d770d31f732d50d3ec373865822fbe659e47c75.tar.gz";
      hash = "sha256-hJ/iXC+3BOlYzK7ihKcalyIrmjfhOA7erW6kgIibsN8=";
    };
  }
  {
    name = "N-V-__8AAExZCQBbT7NCZKdW4KxnVtSRvSVqTtJt0FEqfSa9";
    path = fetchZigArtifact {
      name = "tree_sitter_lua";
      url = "https://github.com/tree-sitter-grammars/tree-sitter-lua/archive/7040a79f95b0bf7517a9809a8d0ecd41197027ac.tar.gz";
      hash = "sha256-W2/4AIo73LOXMyQuLabtkEKT9uTXN6mzQOtwoF7raQg=";
    };
  }
  {
    name = "N-V-__8AAD6dEwA9hwePYcn8FdDAJEeYqCBBlYI2Oey6O5g2";
    path = fetchZigArtifact {
      name = "tree_sitter_make";
      url = "https://github.com/tree-sitter-grammars/tree-sitter-make/archive/5e9e8f8ff3387b0edcaa90f46ddf3629f4cfeb1d.tar.gz";
      hash = "sha256-T77txAmClk01f3nrJ95lBltWGQTeFtB7Fe4VXGe/yFw=";
    };
  }
  {
    name = "N-V-__8AANVLPgC-yBA9l867GoeMn95l0Y_Q9CAzcizA7qlT";
    path = fetchZigArtifact {
      name = "tree_sitter_python";
      url = "https://github.com/tree-sitter/tree-sitter-python/archive/de0c01e7102e755f6c2e1b3055ae6ca85f261a10.tar.gz";
      hash = "sha256-YYgcBGBrMK8yfmudK75W72eBjgkW2ZGuGW9Y02qZ8hQ=";
    };
  }
  {
    name = "N-V-__8AAJ3uaABprqh1hqE6xstGrAJWc4xL3u1HfJ6Plj6E";
    path = fetchZigArtifact {
      name = "tree_sitter_rust";
      url = "https://github.com/tree-sitter/tree-sitter-rust/archive/c447dcce961ac438aaeaf117347749fe7d1e8365.tar.gz";
      hash = "sha256-UXbNM5EK9lJcZhQQnZHePk9+p/MZWGafxZPPffU+UBA=";
    };
  }
  {
    name = "N-V-__8AABBcGwBNXXnYqPiNmGDO5T2k7__Tglt1pwNFI_YN";
    path = fetchZigArtifact {
      name = "tree_sitter_yaml";
      url = "https://github.com/tree-sitter-grammars/tree-sitter-yaml/archive/1805917414a9a8ba2473717fd69447277a175fae.tar.gz";
      hash = "sha256-FMTYaOpWez3Tr3ojFsh9XjE62F9h+6TKewnGGd8zv0I=";
    };
  }
  {
    name = "N-V-__8AAN6NXgCZxLUnqe4620P_FqHrEY8PHTA1-VlOn4yX";
    path = fetchZigArtifact {
      name = "tree_sitter_zig";
      url = "https://github.com/tree-sitter-grammars/tree-sitter-zig/archive/b670c8df85a1568f498aa5c8cae42f51a90473c0.tar.gz";
      hash = "sha256-x69bGpkvyv/fUKEamXT7+PCdIMTZ70IkWskMFS3TqFo=";
    };
  }
  {
    name = "treez-0.2.0-4JX9hV6mAAA-T-vae75m4eZSgIxKsv6uUae21-Dzhh8l";
    path = fetchZigArtifact {
      name = "treez";
      url = "https://github.com/JacobCrabill/treez/archive/980316cb4fd0da6075a6a8f86bd1a3927bf68ad3.tar.gz";
      hash = "sha256-WCWxny8EPydkMRtVp7eIAm8gb5is8yMfGgwZSabANug=";
    };
  }
  {
    name = "N-V-__8AAC3KCQZMd5ea2CkcbjldaVqCT7BT_9_rLMId6V__";
    path = fetchZigArtifact {
      name = "wasmtime_c_api_aarch64_android";
      url = "https://github.com/bytecodealliance/wasmtime/releases/download/v29.0.1/wasmtime-v29.0.1-aarch64-android-c-api.tar.xz";
      hash = "sha256-rtpgW+HHHumpbjzTBeLI8ClbpcpiNBxxQAF/rTyelxM=";
    };
  }
  {
    name = "N-V-__8AAGUY3gU6jj2CNJAYb7HiMNVPV1FIcTCI6RSSYwXu";
    path = fetchZigArtifact {
      name = "wasmtime_c_api_aarch64_linux";
      url = "https://github.com/bytecodealliance/wasmtime/releases/download/v29.0.1/wasmtime-v29.0.1-aarch64-linux-c-api.tar.xz";
      hash = "sha256-erdllfdl1guhTEmOwlUG5RkhPEung/Uqe+xTcLCazm0=";
    };
  }
  {
    name = "N-V-__8AAM1GMARD6LGQebhVsSZ0uePUoo3Fw5nEO2L764vf";
    path = fetchZigArtifact {
      name = "wasmtime_c_api_aarch64_macos";
      url = "https://github.com/bytecodealliance/wasmtime/releases/download/v29.0.1/wasmtime-v29.0.1-aarch64-macos-c-api.tar.xz";
      hash = "sha256-OqhAuiTxQQe8fdm4Kxt7Mezo6kcuBoICUax2yvqHIsA=";
    };
  }
  {
    name = "N-V-__8AAN2cuQadBwMc8zJxv0sMY99Ae1Nc1dZcZAK9b4DZ";
    path = fetchZigArtifact {
      name = "wasmtime_c_api_riscv64gc_linux";
      url = "https://github.com/bytecodealliance/wasmtime/releases/download/v29.0.1/wasmtime-v29.0.1-riscv64gc-linux-c-api.tar.xz";
      hash = "sha256-/mlEWosmgnak//fop94xWrzYiqWXgzfnkDVtZOdBuWw=";
    };
  }
  {
    name = "N-V-__8AAPevngYz99mwT0KQY9my2ax1p6APzgLEJeV4II9U";
    path = fetchZigArtifact {
      name = "wasmtime_c_api_s390x_linux";
      url = "https://github.com/bytecodealliance/wasmtime/releases/download/v29.0.1/wasmtime-v29.0.1-s390x-linux-c-api.tar.xz";
      hash = "sha256-cn/+d/axorHz7VJgqdAACjPkXuqbefupKfFTX1r0zQM=";
    };
  }
  {
    name = "N-V-__8AABHIEgaTyzPfjgnnCy0dwJiXoDiJFblCkYOJsQvy";
    path = fetchZigArtifact {
      name = "wasmtime_c_api_x86_64_android";
      url = "https://github.com/bytecodealliance/wasmtime/releases/download/v29.0.1/wasmtime-v29.0.1-x86_64-android-c-api.tar.xz";
      hash = "sha256-t6alrft8xe6142UaXdYOx3yIJ8imiZdsbJC/4LkJojU=";
    };
  }
  {
    name = "N-V-__8AALUN5AWSEDRulL9u-OJJ-l0_GoT5UFDtGWZayEIq";
    path = fetchZigArtifact {
      name = "wasmtime_c_api_x86_64_linux";
      url = "https://github.com/bytecodealliance/wasmtime/releases/download/v29.0.1/wasmtime-v29.0.1-x86_64-linux-c-api.tar.xz";
      hash = "sha256-J4cVIOAhk7rdWoPhalAJxFNx7F7J4d+DQrShfvw+NbY=";
    };
  }
  {
    name = "N-V-__8AANUeXwSPh13TqJCSSFdi87GEcHs8zK6FqE4v_TjB";
    path = fetchZigArtifact {
      name = "wasmtime_c_api_x86_64_macos";
      url = "https://github.com/bytecodealliance/wasmtime/releases/download/v29.0.1/wasmtime-v29.0.1-x86_64-macos-c-api.tar.xz";
      hash = "sha256-JPvwhFQCQ3xYV7mdeFgxd6haAlyR2ZqTfB4sEewJ/K0=";
    };
  }
  {
    name = "N-V-__8AALundgW-p1ffOnd7bsYyL8SY5OziDUZu7cXio2EL";
    path = fetchZigArtifact {
      name = "wasmtime_c_api_x86_64_mingw";
      url = "https://github.com/bytecodealliance/wasmtime/releases/download/v29.0.1/wasmtime-v29.0.1-x86_64-mingw-c-api.zip";
      hash = "sha256-g3GCHT2gEEF6aG50AUWe27VKMqOI7RKqxk1BJBRiWCY=";
    };
  }
  {
    name = "N-V-__8AALMZ5wXJWW5qY-3MMjTAYR0MusckvzCsmg-69ALH";
    path = fetchZigArtifact {
      name = "wasmtime_c_api_x86_64_musl";
      url = "https://github.com/bytecodealliance/wasmtime/releases/download/v29.0.1/wasmtime-v29.0.1-x86_64-musl-c-api.tar.xz";
      hash = "sha256-IPErCOWrVkz3iuwCv/sVTe+AadO4ZU4E+Uoxkmy5CW8=";
    };
  }
  {
    name = "N-V-__8AAG-uVQVEDMsB1ymJzxpHcoiXo1_I3TFnPM5Zjy1i";
    path = fetchZigArtifact {
      name = "wasmtime_c_api_x86_64_windows";
      url = "https://github.com/bytecodealliance/wasmtime/releases/download/v29.0.1/wasmtime-v29.0.1-x86_64-windows-c-api.zip";
      hash = "sha256-xdhffZEvjSq4Cg2HU5jjYB3g5OMsDVNw4qZ9yJ+wYl8=";
    };
  }
  {
    name = "N-V-__8AAC1yDQBe7ev1_AAguXlIl0g3dEFO_B-s5O_kJJI4";
    path = fetchZigArtifact {
      name = "whatwg_html";
      url = "git+https://github.com/whatwg/html-build/#283a3531a61106d07d9a7d9fb3e6f3b9bfd33d70";
      hash = "sha256-KHmfSliCT40m/jkM/WiBJgQTXEXzTyqicRIhfUvvp/w=";
    };
  }
  {
    name = "zigdown-1.2.1-M06JT5IzFgDTiRC66WcjynfIDs36nQocT40xNfys-wuq";
    path = fetchZigArtifact {
      name = "zigdown";
      url = "https://github.com/JacobCrabill/zigdown/archive/refs/tags/v1.2.1.tar.gz";
      hash = "sha256-hIWv9bTqfIp25YlFfYYIey8I+1C/++AlZaZxaihXUQY=";
    };
  }
  {
    name = "zigfsm-0.2.0-9VW4uQY7AQBrx9lNrVJ3PNRPvAX56jJnLBFOL8-vUN25";
    path = fetchZigArtifact {
      name = "zigfsm";
      url = "git+https://github.com/cryptocode/zigfsm#d4438aa9a28477bcb6f74f11e2875279aa928afd";
      hash = "sha256-pvdh/fCyOvvN11iapDYzkTdJigmxl33uhzrs2IBQkKM=";
    };
  }
  {
    name = "zlua-0.2.0-hGRpC2sYBQCawPfqP3rxM95KUN3IYdRNKTAeSussl7kM";
    path = fetchZigArtifact {
      name = "ziglua";
      url = "https://github.com/JacobCrabill/ziglua/archive/011758bab2c2b5a4b6e678e33a8dbb24570d4394.tar.gz";
      hash = "sha256-U4u2zsRpSp3uSfiBPFM5gauU67mJcpRb6yU7ahdQG68=";
    };
  }
]
