{
  prev,
  slib,
  sources,
  selfSource,
  ...
}:
let
  inherit (selfSource) version;

  upstreamSrc = prev.fetchFromGitHub {
    owner = "block";
    repo = "goose";
    tag = "v${version}";
    hash = slib.sourceHash "goose-cli" "srcHash";
  };

  v8Source = sources.goose-v8;
  v8HashEntry = builtins.head (
    builtins.filter (entry: entry.hashType == "srcHash") (v8Source.hashes or [ ])
  );
  v8ManifestVersion =
    (builtins.fromTOML (builtins.readFile "${rustyV8Src}/Cargo.toml")).package.version;

  prebuiltV8 =
    if prev.stdenv.hostPlatform.isLinux then
      slib.mkRustyV8PrebuiltArtifacts {
        pkgs = prev;
        name = "goose-cli-v8";
        releaseVersion = v8ManifestVersion;
        archiveHash =
          slib.sourceHashForPlatform "goose-v8" "rustyV8ArchiveHash"
            prev.stdenv.hostPlatform.system;
        bindingHash =
          slib.sourceHashForPlatform "goose-v8" "rustyV8BindingHash"
            prev.stdenv.hostPlatform.system;
      }
    else
      null;

  rustyV8Src = prev.fetchgit {
    url = "https://github.com/jh-block/rusty_v8.git";
    rev = v8Source.version;
    fetchSubmodules = true;
    inherit (v8HashEntry) hash;
  };

  v8Build = slib.mkRustyV8Build {
    pkgs = prev;
    name = "goose-cli-v8";
    inherit (v8Source) version;
    inherit rustyV8Src;
    extraPatches = [ ./rusty-v8-goose-rename.patch ];
    prebuiltArtifacts = prebuiltV8;
  };
  patchedV8Src = v8Build.patchedSrc;
  v8NativeDrv = v8Build.nativeDrv;
  inherit (v8Build) chromiumToolchainBundle;

  cargoNixFn = import ./Cargo.nix;
  cargoNixGooseVersion = (cargoNixFn { pkgs = prev; }).internal.crates."goose-cli".version;
  cargoNixV8Version = (cargoNixFn { pkgs = prev; }).internal.crates."v8-goose".version;
  cargoNixVersionCheck =
    if cargoNixGooseVersion == version then
      true
    else
      throw ''
        overlays/goose-cli/Cargo.nix has goose-cli version ${cargoNixGooseVersion},
        expected ${version}; regenerate Cargo.nix
      '';
  cargoNixV8VersionCheck =
    if cargoNixV8Version == v8ManifestVersion then
      true
    else
      throw ''
        overlays/goose-cli/Cargo.nix has v8-goose version ${cargoNixV8Version},
        expected ${v8ManifestVersion}; regenerate Cargo.nix
      '';

  # Hand-maintained source surgery. crate2nix handles the Rust dependency graph,
  # but Goose still needs a custom V8 source tree, lockfile rewrite, and a few
  # build-file tweaks before the workspace is buildable in Nix.
  patchedSrc =
    prev.runCommand "goose-cli-${version}-src"
      {
        nativeBuildInputs = [
          prev.python3
        ];
      }
      ''
        cp -r ${upstreamSrc} $out
        chmod -R u+w $out

        mkdir -p $out/vendor
        cp -r ${patchedV8Src} $out/vendor/v8-goose-src
        chmod -R u+w $out/vendor/v8-goose-src

        ${prev.lib.getExe prev.python3} ${./patch_source.py} "$out"

        cp ${./crate-hashes.json} $out/crate-hashes.json
      '';

  # Generated by crate2nix and post-processed so the checked-in file can point
  # at a separate patched source tree via rootSrc. See README.md for regen flow.
  cargoNix = cargoNixFn {
    pkgs = prev;
    rootSrc = patchedSrc;
  };

  # Common inputs shared by the Goose workspace binaries themselves.
  commonGooseOverride = attrs: {
    nativeBuildInputs = (attrs.nativeBuildInputs or [ ]) ++ [
      prev.pkg-config
      prev.protobuf
    ];

    buildInputs =
      (attrs.buildInputs or [ ])
      ++ [
        prev.dbus
        prev.openssl
      ]
      ++ prev.lib.optionals prev.stdenv.hostPlatform.isLinux [ prev.libxcb ];

    LIBCLANG_PATH = "${prev.lib.getLib prev.llvmPackages.libclang}/lib";
  };

  # xcap only needs the extra X11 bits on Linux.
  xcapLinuxOverride =
    attrs:
    prev.lib.optionalAttrs prev.stdenv.hostPlatform.isLinux {
      buildInputs = (attrs.buildInputs or [ ]) ++ [ prev.libxcb ];
    };

  # llama-cpp-sys-2 expects Cargo-style env plus native CMake tooling that
  # buildRustCrate/crate2nix do not provide out of the box.
  llamaCppSysOverride = attrs: {
    nativeBuildInputs = (attrs.nativeBuildInputs or [ ]) ++ [
      prev.cmake
      prev.pkg-config
      prev.rustPlatform.bindgenHook
    ];

    # buildRustCrate doesn't currently export CARGO_CFG_TARGET_FEATURE even
    # though Cargo build scripts normally see it. llama-cpp-sys uses that env
    # var only to opt into extra x86 GGML toggles, so an empty string is a safe
    # fallback on our darwin/aarch64 builds.
    CARGO_CFG_TARGET_FEATURE = "";
    CMAKE_BUILD_PARALLEL_LEVEL = "1";
    LIBCLANG_PATH = "${prev.lib.getLib prev.llvmPackages.libclang}/lib";
  };

  # hipstr 0.6.0's serde path assumes serde_bytes is available; patch the
  # transitive crate instead of carrying a Goose-specific workaround.
  hipstrOverride = attrs: {
    patches = (attrs.patches or [ ]) ++ [ ./hipstr-no-serde-bytes.patch ];
  };

  # rmcp uses env! for Cargo package vars during compilation, but
  # buildRustCrate does not export those automatically.
  rmcpOverride =
    attrs:
    assert attrs ? crateName;
    assert attrs ? version;
    {
      CARGO_CRATE_NAME = attrs.crateName;
      CARGO_PKG_VERSION = attrs.version;
    };

  # V8 crate override: delegates to the shared rusty-v8 builder.
  v8GooseOverride = v8Build.mkCrateOverride;

  # Keep all build-system compatibility shims in one place so version bumps can
  # be audited crate-by-crate.
  crateOverrides = prev.defaultCrateOverrides // {
    goose-cli = commonGooseOverride;
    goose-server = commonGooseOverride;
    hipstr = hipstrOverride;
    llama-cpp-sys-2 = llamaCppSysOverride;
    rmcp = rmcpOverride;
    v8-goose = v8GooseOverride;
    xcap = xcapLinuxOverride;
  };

  # Build the two workspace binaries separately, then rejoin them below to keep
  # the historical goose-cli package shape.
  gooseCliDrv = cargoNix.workspaceMembers.goose-cli.build.override {
    inherit crateOverrides;
    runTests = false;
  };

  gooseCliDrvChecked = gooseCliDrv.overrideAttrs (old: {
    doInstallCheck = true;
    nativeInstallCheckInputs = (old.nativeInstallCheckInputs or [ ]) ++ [ prev.coreutils ];
    installCheckPhase = ''
      runHook preInstallCheck

      export HOME="$(${prev.coreutils}/bin/mktemp -d)"
      export XDG_CACHE_HOME="$(${prev.coreutils}/bin/mktemp -d)"
      export XDG_CONFIG_HOME="$(${prev.coreutils}/bin/mktemp -d)"
      export XDG_DATA_HOME="$(${prev.coreutils}/bin/mktemp -d)"
      export XDG_STATE_HOME="$(${prev.coreutils}/bin/mktemp -d)"

      $out/bin/goose --version
      $out/bin/goose info

      runHook postInstallCheck
    '';
  });

  gooseServerDrv = cargoNix.workspaceMembers.goose-server.build.override {
    inherit crateOverrides;
    runTests = false;
  };

  workspaceBins = prev.symlinkJoin {
    name = "goose-cli-workspace-${version}";
    paths = [
      gooseCliDrvChecked
      gooseServerDrv
    ];
  };
in
{
  goose-cli-crate2nix-src = patchedSrc;
  goose-cli =
    assert cargoNixVersionCheck;
    assert cargoNixV8VersionCheck;
    prev.symlinkJoin {
      name = "goose-cli-${version}";
      paths = [ workspaceBins ];
      nativeBuildInputs = [ prev.installShellFiles ];

      postBuild = ''
        rm -f $out/bin/generate_manpages $out/bin/generate_schema

        export HOME="$TMPDIR/home"
        export XDG_CACHE_HOME="$TMPDIR/xdg-cache"
        export XDG_CONFIG_HOME="$TMPDIR/xdg-config"
        export XDG_DATA_HOME="$TMPDIR/xdg-data"
        export XDG_STATE_HOME="$TMPDIR/xdg-state"
        mkdir -p \
          "$HOME" \
          "$XDG_CACHE_HOME" \
          "$XDG_CONFIG_HOME" \
          "$XDG_DATA_HOME" \
          "$XDG_STATE_HOME"

        installShellCompletion --cmd goose \
          --bash <($out/bin/goose completion bash) \
          --fish <($out/bin/goose completion fish) \
          --zsh <($out/bin/goose completion zsh)
      '';

      passthru = {
        inherit
          cargoNix
          crateOverrides
          gooseServerDrv
          patchedSrc
          patchedV8Src
          chromiumToolchainBundle
          v8Build
          ;
        gooseCliDrv = gooseCliDrvChecked;
        inherit v8NativeDrv;
      };

      meta = {
        description = "Open-source, extensible AI agent that goes beyond code suggestions - install, execute, edit, and test with any LLM";
        homepage = "https://github.com/block/goose";
        license = prev.lib.licenses.asl20;
        mainProgram = "goose";
        platforms = [
          "aarch64-darwin"
          "x86_64-linux"
        ];
      };
    };
}
