"""Internal Python rendering and post-processing helpers."""

from __future__ import annotations

import ast
import importlib
import io
import json
import re
import tempfile
import tokenize
from pathlib import Path
from typing import Protocol, cast

from lib import codegen_utils, json_utils
from lib.schema_codegen.config import CodegenTarget, PythonTransform

type JsonValue = json_utils.JsonValue


class _GenerateConfigModel(Protocol):
    @classmethod
    def model_validate(cls, obj: object) -> object: ...


class _DataModelCodeGeneratorConfigModule(Protocol):
    GenerateConfig: type[_GenerateConfigModel]


class _DataModelCodeGeneratorModule(Protocol):
    def generate(
        self, source: Path | str | object, *, config: object
    ) -> str | None | object: ...


_rewrite_constr_type_hints = codegen_utils.rewrite_constr_type_hints
_normalize_pydantic_imports = codegen_utils.normalize_pydantic_imports


def _import_optional(module_name: str, *, feature: str) -> object:
    """Import an optional dependency or raise a helpful runtime error."""
    try:
        return importlib.import_module(module_name)
    except ModuleNotFoundError as exc:  # pragma: no cover - exercised in live CLI
        msg = (
            f"{feature} requires optional dependency {module_name!r}. "
            "Install the `codegen` extra to use this command."
        )
        raise RuntimeError(msg) from exc


def normalize_entrypoint_name(entrypoint: str) -> str:
    """Return a stable label for generated per-entrypoint sections."""
    candidate = entrypoint.rsplit("/", maxsplit=1)[-1].removesuffix(".yaml")
    candidate = candidate.removesuffix(".yml").removesuffix(".json")
    return candidate or "schema"


def strip_generated_headers(code: str) -> str:
    """Remove datamodel-code-generator headers before composing outputs."""
    filtered: list[str] = []
    for line in code.splitlines():
        if line.startswith("# generated by datamodel-codegen"):
            continue
        if line.startswith("#   filename:"):
            continue
        if line.startswith("#   timestamp:"):
            continue
        filtered.append(line)
    return "\n".join(filtered)


def collect_imports(code: str) -> tuple[set[str], str]:
    """Extract import statements and return them separately from the body."""
    tree = ast.parse(code)
    lines = code.splitlines()
    imports: set[str] = set()
    import_line_numbers: set[int] = set()

    for node in tree.body:
        if not isinstance(node, (ast.Import, ast.ImportFrom)):
            continue
        start = node.lineno - 1
        end = node.end_lineno if node.end_lineno is not None else node.lineno
        imports.add("\n".join(lines[start:end]))
        import_line_numbers.update(range(start, end))

    body = [
        line for index, line in enumerate(lines) if index not in import_line_numbers
    ]
    return imports, "\n".join(body)


def _format_import_alias(alias: ast.alias) -> str:
    """Render one import alias back to source form."""
    return alias.name if alias.asname is None else f"{alias.name} as {alias.asname}"


def _import_module_sort_key(module: str) -> tuple[int, str]:
    """Sort stdlib imports ahead of third-party imports."""
    return (1 if module.startswith("pydantic") else 0, module)


def compose_imports_block(all_imports: set[str]) -> str:
    """Compose one deduplicated import block."""
    from_imports: dict[str, set[str]] = {}
    bare_imports: set[str] = set()
    for import_stmt in all_imports:
        node = ast.parse(import_stmt).body[0]
        if isinstance(node, ast.ImportFrom):
            module_name = node.module or ""
            if module_name == "__future__":
                continue
            from_imports.setdefault(module_name, set()).update(
                _format_import_alias(alias) for alias in node.names
            )
        elif isinstance(node, ast.Import):
            bare_imports.update(_format_import_alias(alias) for alias in node.names)

    lines: list[str] = [f"import {name}" for name in sorted(bare_imports)]
    previous_group: int | None = None
    for module_name in sorted(from_imports, key=_import_module_sort_key):
        group, _ = _import_module_sort_key(module_name)
        if (
            previous_group is not None
            and group != previous_group
            and lines
            and lines[-1] != ""
        ):
            lines.append("")
        lines.append(
            f"from {module_name} import {', '.join(sorted(from_imports[module_name]))}"
        )
        previous_group = group
    return "\n".join(lines)


def entrypoint_class_suffix(entrypoint: str) -> str:
    """Return a stable CamelCase suffix derived from one entrypoint label."""
    parts = re.findall(r"[A-Za-z0-9]+", normalize_entrypoint_name(entrypoint))
    return "".join(part.capitalize() for part in parts) or "Schema"


def _class_signature(node: ast.ClassDef) -> str:
    """Return one class definition's semantic signature for dedupe checks."""
    return ast.dump(node, annotate_fields=True, include_attributes=False)


def _rename_name_tokens(code: str, *, rename_map: dict[str, str]) -> str:
    """Rename Python identifiers without touching strings or comments."""
    if not rename_map:
        return code
    tokens: list[tokenize.TokenInfo] = []
    for token_info in tokenize.generate_tokens(io.StringIO(code).readline):
        replacement = token_info
        if token_info.type == tokenize.NAME and token_info.string in rename_map:
            replacement = tokenize.TokenInfo(
                type=token_info.type,
                string=rename_map[token_info.string],
                start=token_info.start,
                end=token_info.end,
                line=token_info.line,
            )
        tokens.append(replacement)
    return tokenize.untokenize(tokens)


def resolve_body_class_conflicts(
    body: str,
    *,
    entrypoint: str,
    seen_signatures: dict[str, str],
    used_names: set[str],
) -> str:
    """Rename conflicting helper classes and drop byte-identical duplicates."""
    tree = ast.parse(body)
    drop_lines: set[int] = set()
    rename_map: dict[str, str] = {}
    suffix = entrypoint_class_suffix(entrypoint)

    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        signature = _class_signature(node)
        previous = seen_signatures.get(node.name)
        if previous is None:
            seen_signatures[node.name] = signature
            used_names.add(node.name)
            continue
        if previous == signature:
            end = node.end_lineno if node.end_lineno is not None else node.lineno
            drop_lines.update(range(node.lineno - 1, end))
            continue

        candidate = f"{node.name}{suffix}"
        counter = 2
        while candidate in used_names:
            candidate = f"{node.name}{suffix}{counter}"
            counter += 1
        rename_map[node.name] = candidate
        used_names.add(candidate)
        seen_signatures[candidate] = signature

    rewritten = _rename_name_tokens(body, rename_map=rename_map)
    if not drop_lines:
        return rewritten
    return "\n".join(
        line
        for index, line in enumerate(rewritten.splitlines())
        if index not in drop_lines
    )


def dedupe_classes(code: str) -> str:
    """Keep only the first generated definition for duplicate class names."""
    seen_classes: set[str] = set()
    deduped: list[str] = []
    skip_body = False
    for line in code.splitlines():
        class_match = re.match(r"^class (\w+)\(", line)
        if class_match:
            class_name = class_match.group(1)
            if class_name in seen_classes:
                skip_body = True
                continue
            seen_classes.add(class_name)
            skip_body = False
        elif skip_body:
            if line.strip() == "" or (line and not line[0].isspace()):
                skip_body = False
            else:
                continue
        deduped.append(line)
    return "\n".join(deduped)


def collapse_excess_blank_lines(code: str) -> str:
    """Trim long blank-line runs introduced during composition."""
    return re.sub(r"\n{4,}", "\n\n\n", code)


def apply_python_transforms(code: str, *, target: CodegenTarget) -> str:
    """Apply configured Python post-processing transforms to generated code."""
    transforms = set(target.prepare.python_transforms)
    if PythonTransform.REWRITE_CONSTR_ANNOTATIONS in transforms:
        code = _rewrite_constr_type_hints(code)
    if PythonTransform.NORMALIZE_PYDANTIC_IMPORTS in transforms:
        code = _normalize_pydantic_imports(code)
    return code


def _map_generator_options(options: dict[str, object]) -> object:
    """Validate config values with upstream ``GenerateConfig`` directly."""
    config_mod = cast(
        "_DataModelCodeGeneratorConfigModule",
        _import_optional(
            "datamodel_code_generator.config",
            feature="schema code generation",
        ),
    )
    mapped = dict(options)
    mapped.pop("output", None)
    return config_mod.GenerateConfig.model_validate(mapped)


def generate_models(
    *,
    entrypoint: str,
    generator_options: dict[str, object],
    schema: JsonValue,
) -> str:
    """Generate Python models for one fully-prepared schema entrypoint.

    We materialize the prepared schema to a temporary file before invoking
    ``datamodel-code-generator`` so any remaining in-document ``$ref`` values
    still resolve against a real schema file. This keeps recursive/internal
    references working for targets that intentionally skip inline dereference.
    """
    datamodel_code_generator = cast(
        "_DataModelCodeGeneratorModule",
        _import_optional("datamodel_code_generator", feature="schema code generation"),
    )
    schema_filename = f"{normalize_entrypoint_name(entrypoint)}.json"
    config = _map_generator_options({
        **generator_options,
        "input_filename": schema_filename,
    })
    schema_json = json.dumps(schema, indent=2)
    with tempfile.TemporaryDirectory(prefix="nixcfg-schema-codegen-") as temp_dir:
        schema_path = Path(temp_dir) / schema_filename
        schema_path.write_text(f"{schema_json}\n", encoding="utf-8")
        result = datamodel_code_generator.generate(schema_path, config=config)
    if result is None:
        msg = f"codegen returned None for {entrypoint}"
        raise RuntimeError(msg)
    return result if isinstance(result, str) else str(result)
