"""Internal Python rendering and post-processing helpers."""

from __future__ import annotations

import ast
import importlib
import json
import re
import tempfile
from pathlib import Path
from typing import Protocol, cast, override

import isort
import libcst as cst

from lib import codegen_utils, json_utils
from lib.schema_codegen.config import CodegenTarget, PythonTransform

type JsonValue = json_utils.JsonValue


class _GenerateConfigModel(Protocol):
    @classmethod
    def model_validate(cls, obj: object) -> object: ...


class _DataModelCodeGeneratorConfigModule(Protocol):
    GenerateConfig: type[_GenerateConfigModel]


class _DataModelCodeGeneratorModule(Protocol):
    def generate(
        self, source: Path | str | object, *, config: object
    ) -> str | None | object: ...


_rewrite_constr_type_hints = codegen_utils.rewrite_constr_type_hints
_normalize_pydantic_imports = codegen_utils.normalize_pydantic_imports


def _import_optional(module_name: str, *, feature: str) -> object:
    """Import an optional dependency or raise a helpful runtime error."""
    try:
        return importlib.import_module(module_name)
    except ModuleNotFoundError as exc:  # pragma: no cover - exercised in live CLI
        msg = (
            f"{feature} requires optional dependency {module_name!r}. "
            "Install the `codegen` extra to use this command."
        )
        raise RuntimeError(msg) from exc


def normalize_entrypoint_name(entrypoint: str) -> str:
    """Return a stable label for generated per-entrypoint sections."""
    candidate = entrypoint.rsplit("/", maxsplit=1)[-1].removesuffix(".yaml")
    candidate = candidate.removesuffix(".yml").removesuffix(".json")
    return candidate or "schema"


def strip_generated_headers(code: str) -> str:
    """Remove datamodel-code-generator headers before composing outputs."""
    filtered: list[str] = []
    for line in code.splitlines():
        if line.startswith("# generated by datamodel-codegen"):
            continue
        if line.startswith("#   filename:"):
            continue
        if line.startswith("#   timestamp:"):
            continue
        filtered.append(line)
    return "\n".join(filtered)


def collect_imports(code: str) -> tuple[set[str], str]:
    """Extract import statements and return them separately from the body."""
    imports: set[str] = set()
    body: list[cst.CSTNode] = []
    module = cst.parse_module(code)

    for statement in module.body:
        if isinstance(statement, cst.SimpleStatementLine) and all(
            isinstance(item, cst.Import | cst.ImportFrom) for item in statement.body
        ):
            imports.add(module.code_for_node(statement).strip())
            continue
        body.append(statement)

    return imports, module.with_changes(body=tuple(body)).code.strip("\n")


def _format_import_alias(alias: ast.alias) -> str:
    """Render one import alias back to source form."""
    return alias.name if alias.asname is None else f"{alias.name} as {alias.asname}"


def _import_module_sort_key(module: str) -> tuple[int, str]:
    """Sort stdlib imports ahead of third-party imports."""
    return (1 if module.startswith("pydantic") else 0, module)


def compose_imports_block(all_imports: set[str]) -> str:
    """Compose one deduplicated import block."""
    import_lines: list[str] = []
    for import_stmt in all_imports:
        try:
            module = cst.parse_module(import_stmt)
        except cst.ParserSyntaxError:
            continue
        if len(module.body) != 1:
            continue
        [statement] = module.body
        if not isinstance(statement, cst.SimpleStatementLine):
            continue
        if not all(
            isinstance(item, cst.Import | cst.ImportFrom) for item in statement.body
        ):
            continue
        if any(
            isinstance(item, cst.ImportFrom)
            and isinstance(item.module, cst.Name)
            and item.module.value == "__future__"
            for item in statement.body
        ):
            continue
        import_lines.append(module.code.strip())

    if not import_lines:
        return ""
    return isort.code("\n".join(sorted(set(import_lines))) + "\n").strip()


def entrypoint_class_suffix(entrypoint: str) -> str:
    """Return a stable CamelCase suffix derived from one entrypoint label."""
    parts = re.findall(r"[A-Za-z0-9]+", normalize_entrypoint_name(entrypoint))
    return "".join(part.capitalize() for part in parts) or "Schema"


def _class_signature(node: ast.ClassDef) -> str:
    """Return one class definition's semantic signature for dedupe checks."""
    return ast.dump(node, annotate_fields=True, include_attributes=False)


def _rename_name_tokens(code: str, *, rename_map: dict[str, str]) -> str:
    """Rename Python identifiers without touching strings or comments."""
    if not rename_map:
        return code

    class _RenameTransformer(cst.CSTTransformer):
        @override
        def leave_Name(
            self, original_node: cst.Name, updated_node: cst.Name
        ) -> cst.Name:
            _ = original_node
            replacement = rename_map.get(updated_node.value)
            if replacement is None:
                return updated_node
            return updated_node.with_changes(value=replacement)

    return cst.parse_module(code).visit(_RenameTransformer()).code


class _TopLevelClassDedupe(cst.CSTTransformer):
    """Remove duplicate top-level class definitions after composition."""

    def __init__(self) -> None:
        self._dropped_class = False

    @override
    def leave_Module(
        self, original_node: cst.Module, updated_node: cst.Module
    ) -> cst.Module:
        _ = original_node
        seen_classes: set[str] = set()
        body: list[cst.CSTNode] = []
        for statement in updated_node.body:
            next_statement = statement
            if isinstance(statement, cst.ClassDef):
                class_name = statement.name.value
                if class_name in seen_classes:
                    self._dropped_class = True
                    continue
                seen_classes.add(class_name)
            if self._dropped_class and hasattr(statement, "leading_lines"):
                leading_lines = tuple(statement.leading_lines)
                if not leading_lines:
                    next_statement = statement.with_changes(
                        leading_lines=(cst.EmptyLine(),)
                    )
                self._dropped_class = False
            body.append(next_statement)
        return updated_node.with_changes(body=tuple(body))


def resolve_body_class_conflicts(
    body: str,
    *,
    entrypoint: str,
    seen_signatures: dict[str, str],
    used_names: set[str],
) -> str:
    """Rename conflicting helper classes and drop byte-identical duplicates."""
    tree = ast.parse(body)
    drop_lines: set[int] = set()
    rename_map: dict[str, str] = {}
    suffix = entrypoint_class_suffix(entrypoint)

    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        signature = _class_signature(node)
        previous = seen_signatures.get(node.name)
        if previous is None:
            seen_signatures[node.name] = signature
            used_names.add(node.name)
            continue
        if previous == signature:
            end = node.end_lineno if node.end_lineno is not None else node.lineno
            drop_lines.update(range(node.lineno - 1, end))
            continue

        candidate = f"{node.name}{suffix}"
        counter = 2
        while candidate in used_names:
            candidate = f"{node.name}{suffix}{counter}"
            counter += 1
        rename_map[node.name] = candidate
        used_names.add(candidate)
        seen_signatures[candidate] = signature

    rewritten = _rename_name_tokens(body, rename_map=rename_map)
    if not drop_lines:
        return rewritten
    return "\n".join(
        line
        for index, line in enumerate(rewritten.splitlines())
        if index not in drop_lines
    )


def dedupe_classes(code: str) -> str:
    """Keep only the first generated definition for duplicate class names."""
    return cst.parse_module(code).visit(_TopLevelClassDedupe()).code.rstrip("\n")


def collapse_excess_blank_lines(code: str) -> str:
    """Trim long blank-line runs introduced during composition."""
    return re.sub(r"\n{4,}", "\n\n\n", code)


def apply_python_transforms(code: str, *, target: CodegenTarget) -> str:
    """Apply configured Python post-processing transforms to generated code."""
    transforms = set(target.prepare.python_transforms)
    if PythonTransform.REWRITE_CONSTR_ANNOTATIONS in transforms:
        code = _rewrite_constr_type_hints(code)
    if PythonTransform.NORMALIZE_PYDANTIC_IMPORTS in transforms:
        code = _normalize_pydantic_imports(code)
    return code


def _map_generator_options(options: dict[str, object]) -> object:
    """Validate config values with upstream ``GenerateConfig`` directly."""
    config_mod = cast(
        "_DataModelCodeGeneratorConfigModule",
        _import_optional(
            "datamodel_code_generator.config",
            feature="schema code generation",
        ),
    )
    mapped = dict(options)
    mapped.pop("output", None)
    return config_mod.GenerateConfig.model_validate(mapped)


def generate_models(
    *,
    entrypoint: str,
    generator_options: dict[str, object],
    schema: JsonValue,
) -> str:
    """Generate Python models for one fully-prepared schema entrypoint.

    We materialize the prepared schema to a temporary file before invoking
    ``datamodel-code-generator`` so any remaining in-document ``$ref`` values
    still resolve against a real schema file. This keeps recursive/internal
    references working for targets that intentionally skip inline dereference.
    """
    datamodel_code_generator = cast(
        "_DataModelCodeGeneratorModule",
        _import_optional("datamodel_code_generator", feature="schema code generation"),
    )
    schema_filename = f"{normalize_entrypoint_name(entrypoint)}.json"
    config = _map_generator_options({
        **generator_options,
        "input_filename": schema_filename,
    })
    schema_json = json.dumps(schema, indent=2)
    with tempfile.TemporaryDirectory(prefix="nixcfg-schema-codegen-") as temp_dir:
        schema_path = Path(temp_dir) / schema_filename
        schema_path.write_text(f"{schema_json}\n", encoding="utf-8")
        result = datamodel_code_generator.generate(schema_path, config=config)
    if result is None:
        msg = f"codegen returned None for {entrypoint}"
        raise RuntimeError(msg)
    return result if isinstance(result, str) else str(result)
