{ lib, pkgs, ... }:
{
  home.packages =
    with pkgs;
    [
      (coreutils.override { minimal = false; })
      amp-cli
      ast-grep
      axiom-cli
      beads
      beads-mcp
      biome
      cachix
      cargo-update
      code-cursor
      crush
      csvlens
      curator
      curl
      curlie
      czkawka
      dasel
      dbeaver-bin
      deno
      dua
      duf
      dust
      file
      gawk
      git-who
      gita
      gitbutler
      glab
      gnused
      gnutar
      gping
      graphviz
      grex
      hoppscotch
      httpie
      jetbrains.datagrip
      jnv
      jo
      killport
      mdq
      moreutils
      mountpoint-s3
      nerd-fonts.hack
      nil
      nix-output-monitor
      nix-tree
      nixfmt
      nodejs_latest
      postman
      procs
      red-reddit-cli
      rsync
      rustup
      sd
      sentry-cli
      sequoia-chameleon-gnupg
      sequoia-sq
      sequoia-sqop
      sequoia-sqv
      sequoia-wot
      slack
      spacedrive
      spotify
      toad
      tokei
      trdsql
      tree
      viddy
      xan
      xq-xml
      xz
      yq-go
    ]
    ++ lib.lists.optionals pkgs.stdenv.isLinux [ wl-clipboard ]
    ++ lib.lists.optionals pkgs.stdenv.isDarwin [
      appcleaner
      chatgpt
      container
      cyberduck
      google-chrome
      iina
      mas
      notion-app
      rapidapi
      sloth-app
    ];
}
