// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package codegenlock

import "time"

// Resolved source pins and integrity metadata for a code generation manifest.
type CodegenLockfile struct {
	// Informational lockfile timestamp. Omit by default in reproducible output.
	GeneratedAt *time.Time `json:"generated_at,omitempty" yaml:"generated_at,omitempty" mapstructure:"generated_at,omitempty"`

	// Normalized relative POSIX path from the lockfile directory to the manifest
	// file.
	ManifestPath *string `json:"manifest_path,omitempty" yaml:"manifest_path,omitempty" mapstructure:"manifest_path,omitempty"`

	// Sources corresponds to the JSON schema field "sources".
	Sources LockedSourceMap `json:"sources" yaml:"sources" mapstructure:"sources"`

	// Lockfile format version.
	Version int `json:"version" yaml:"version" mapstructure:"version"`
}

type HttpsUrl string

type Identifier string

type LockedDirectorySource struct {
	// Optional digest of the materialized directory file set: sort matched relative
	// paths, append '<path>\0<file-sha256>\n' records, then SHA-256 the UTF-8 bytes.
	ContentSha256 *Sha256Hex `json:"content_sha256,omitempty" yaml:"content_sha256,omitempty" mapstructure:"content_sha256,omitempty"`

	// Informational digest timestamp. Omit by default in reproducible output.
	GeneratedAt *time.Time `json:"generated_at,omitempty" yaml:"generated_at,omitempty" mapstructure:"generated_at,omitempty"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Path corresponds to the JSON schema field "path".
	Path PathString `json:"path" yaml:"path" mapstructure:"path"`
}

type LockedGitHubRawSource struct {
	// Informational fetch timestamp. Omit by default in reproducible output.
	FetchedAt *time.Time `json:"fetched_at,omitempty" yaml:"fetched_at,omitempty" mapstructure:"fetched_at,omitempty"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Owner corresponds to the JSON schema field "owner".
	Owner Identifier `json:"owner" yaml:"owner" mapstructure:"owner"`

	// Informational upstream package name for provenance and diagnostics.
	Package *NonEmptyString `json:"package,omitempty" yaml:"package,omitempty" mapstructure:"package,omitempty"`

	// Informational upstream package version for provenance and diagnostics.
	PackageVersion *NonEmptyString `json:"package_version,omitempty" yaml:"package_version,omitempty" mapstructure:"package_version,omitempty"`

	// Path corresponds to the JSON schema field "path".
	Path PathString `json:"path" yaml:"path" mapstructure:"path"`

	// Immutable commit SHA actually fetched. Original tag or branch provenance may be
	// preserved separately as metadata.
	Ref NonEmptyString `json:"ref" yaml:"ref" mapstructure:"ref"`

	// Repo corresponds to the JSON schema field "repo".
	Repo NonEmptyString `json:"repo" yaml:"repo" mapstructure:"repo"`

	// Sha256 corresponds to the JSON schema field "sha256".
	Sha256 Sha256Hex `json:"sha256" yaml:"sha256" mapstructure:"sha256"`

	// Informational original tag name, when the manifest pinned a tag that resolved
	// to the stored commit SHA.
	Tag *NonEmptyString `json:"tag,omitempty" yaml:"tag,omitempty" mapstructure:"tag,omitempty"`

	// Uri corresponds to the JSON schema field "uri".
	Uri HttpsUrl `json:"uri" yaml:"uri" mapstructure:"uri"`
}

type LockedSource interface{}

type LockedSourceMap map[string]LockedSource

type LockedUrlSource struct {
	// Informational HTTP ETag metadata from the fetch response. Omit by default in
	// reproducible output.
	Etag *NonEmptyString `json:"etag,omitempty" yaml:"etag,omitempty" mapstructure:"etag,omitempty"`

	// Informational fetch timestamp. Omit by default in reproducible output.
	FetchedAt *time.Time `json:"fetched_at,omitempty" yaml:"fetched_at,omitempty" mapstructure:"fetched_at,omitempty"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Informational HTTP Last-Modified metadata from the fetch response. Omit by
	// default in reproducible output.
	LastModified *NonEmptyString `json:"last_modified,omitempty" yaml:"last_modified,omitempty" mapstructure:"last_modified,omitempty"`

	// Sha256 corresponds to the JSON schema field "sha256".
	Sha256 Sha256Hex `json:"sha256" yaml:"sha256" mapstructure:"sha256"`

	// Uri corresponds to the JSON schema field "uri".
	Uri HttpsUrl `json:"uri" yaml:"uri" mapstructure:"uri"`
}

type NonEmptyString string

// POSIX-style path string using '/' separators and no leading './'.
type PathString string

// Lowercase hexadecimal SHA-256 digest.
type Sha256Hex string
