"""Tests for the crate2nix CI helper command."""

from __future__ import annotations

import asyncio
import os
import subprocess
from functools import cache
from pathlib import Path

import pytest
from nix_manipulator.expressions.binding import Binding
from nix_manipulator.expressions.function.definition import FunctionDefinition
from nix_manipulator.expressions.list import NixList
from nix_manipulator.expressions.primitive import Primitive
from nix_manipulator.expressions.set import AttributeSet

from lib.tests._assertions import expect_instance
from lib.tests._nix_ast import (
    assert_nix_ast_equal,
    expect_binding,
    expect_scope_binding,
    parse_nix_expr,
)
from lib.update import crate2nix
from lib.update.events import UpdateEvent, UpdateEventKind, expect_artifact_updates


@cache
def _registry_expr() -> AttributeSet:
    """Return the package registry attrset, including its let-scope bindings."""
    root = expect_instance(
        parse_nix_expr(
            (crate2nix.REPO_ROOT / "packages/registry.nix").read_text(encoding="utf-8")
        ),
        FunctionDefinition,
    )
    return expect_instance(root.output, AttributeSet)


def _constraint_value(value: Primitive | NixList) -> str | list[str] | None:
    """Decode one simple registry constraint literal."""
    if isinstance(value, NixList):
        decoded = [expect_instance(item, Primitive).value for item in value.value]
        assert all(isinstance(item, str) for item in decoded)
        return decoded
    decoded = expect_instance(value, Primitive).value
    assert decoded is None or isinstance(decoded, str)
    return decoded


def _registry_overrides() -> dict[str, dict[str, object]]:
    """Decode the literal override metadata table used by the registry."""
    overrides = expect_instance(
        expect_scope_binding(_registry_expr(), "packageMetadataOverrides").value,
        AttributeSet,
    )
    decoded: dict[str, dict[str, object]] = {}
    for binding in overrides.values:
        entry = expect_instance(binding, Binding)
        entry_value = expect_instance(entry.value, AttributeSet)
        metadata: dict[str, object] = {}
        for meta in entry_value.values:
            field = expect_instance(meta, Binding)
            if field.name == "helper":
                metadata[field.name] = expect_instance(field.value, Primitive).value
                continue
            assert field.name == "constraint"
            metadata[field.name] = _constraint_value(field.value)
        decoded[entry.name.strip('"')] = metadata
    return decoded


def _supports_system(constraint: object, system: str) -> bool:
    """Mirror the tiny system-constraint contract exported by ``packages/registry.nix``."""
    if constraint is None:
        return True
    if isinstance(constraint, list):
        return system in constraint
    assert constraint == "darwin"
    return system.endswith("-darwin")


def test_normalize_json_text_sorts_keys_and_adds_newline() -> None:
    """Canonical JSON rendering should be stable for crate-hashes.json."""
    rendered = crate2nix._normalize_json_text('{"b":1,"a":2}')
    assert rendered == '{\n  "a": 2,\n  "b": 1\n}\n'


def test_normalize_trailing_newline_collapses_extra_newlines() -> None:
    """Generated artifacts should always end with exactly one newline."""
    assert crate2nix._normalize_trailing_newline("demo") == "demo\n"
    assert crate2nix._normalize_trailing_newline("demo\n") == "demo\n"
    assert crate2nix._normalize_trailing_newline("demo\n\n") == "demo\n"


def test_stabilize_generated_command_comment_rewrites_dynamic_paths() -> None:
    """Generated command comments should use stable repo-relative output paths."""
    target = crate2nix.Crate2NixTarget(
        name="demo",
        patched_src_installable="path:.#demo",
        cargo_nix=Path("demo/Cargo.nix"),
        crate_hashes=Path("demo/crate-hashes.json"),
        normalizer_path=Path("demo/normalize.py"),
        supported_platforms=("linux",),
    )
    refreshed = (
        "# This file was @generated by crate2nix 0.15.0 with the command:\n"
        '#   "generate" "-f" "./Cargo.toml" "-o" "/tmp/Cargo.nix" '
        '"-h" "/tmp/crate-hashes.json" "--default-features"\n'
        "# See https://github.com/kolloch/crate2nix for more info.\n"
        "{ }\n"
    )

    stabilized = crate2nix._stabilize_generated_command_comment(target, refreshed)

    assert (
        '#   "generate" "-f" "Cargo.toml" "-o" "demo/Cargo.nix" '
        '"-h" "demo/crate-hashes.json" "--default-features"\n' in stabilized
    )


def test_stabilize_generated_command_comment_preserves_nested_manifest_path() -> None:
    """Nested-manifest targets should keep their real manifest path in comments."""
    target = crate2nix.Crate2NixTarget(
        name="demo",
        patched_src_installable="path:.#demo",
        cargo_nix=Path("demo/Cargo.nix"),
        crate_hashes=Path("demo/crate-hashes.json"),
        normalizer_path=Path("demo/normalize.py"),
        supported_platforms=("linux",),
        cargo_manifest_relpath=Path("packages/desktop/src-tauri/Cargo.toml"),
    )
    refreshed = (
        "# This file was @generated by crate2nix 0.15.0 with the command:\n"
        '#   "generate" "-f" "/tmp/Cargo.toml" "-o" "/tmp/Cargo.nix" '
        '"-h" "/tmp/crate-hashes.json" "--default-features"\n'
        "# See https://github.com/kolloch/crate2nix for more info.\n"
        "{ }\n"
    )

    stabilized = crate2nix._stabilize_generated_command_comment(target, refreshed)

    assert (
        '#   "generate" "-f" "packages/desktop/src-tauri/Cargo.toml" '
        '"-o" "demo/Cargo.nix" "-h" "demo/crate-hashes.json" '
        '"--default-features"\n' in stabilized
    )


def test_stabilize_generated_command_comment_leaves_unrelated_text_unchanged() -> None:
    """Non-generated comments should pass through unchanged."""
    target = crate2nix.Crate2NixTarget(
        name="demo",
        patched_src_installable="path:.#demo",
        cargo_nix=Path("demo/Cargo.nix"),
        crate_hashes=Path("demo/crate-hashes.json"),
        normalizer_path=Path("demo/normalize.py"),
        supported_platforms=("linux",),
    )
    refreshed = (
        "# This file was @generated by crate2nix 0.15.0 with the command:\n"
        "# no command here\n"
        "# See https://github.com/kolloch/crate2nix for more info.\n"
        "{ }\n"
    )

    assert (
        crate2nix._stabilize_generated_command_comment(target, refreshed) == refreshed
    )


def test_stabilize_generated_root_src_paths_rewrites_relative_store_paths() -> None:
    """Store-relative crate source paths should normalize back to ``${rootSrc}``."""
    patched_src = Path("/nix/store/demo-src")
    generated_cargo = Path("/tmp/build/Cargo.nix")
    relative_src = os.path.relpath(
        patched_src / "crates/demo",
        generated_cargo.parent,
    ).replace(os.sep, "/")
    refreshed = (
        "        src = lib.cleanSourceWith { filter = sourceFilter;  "
        f"src = {relative_src}; }};\n"
    )

    stabilized = crate2nix._stabilize_generated_root_src_paths(
        refreshed,
        patched_src=patched_src,
        generated_cargo=generated_cargo,
    )

    assert (
        "src = lib.cleanSourceWith { filter = sourceFilter;  "
        'src = "${rootSrc}/crates/demo"; };\n' in stabilized
    )


def test_stabilize_generated_root_src_paths_handles_root_and_unrelated_paths() -> None:
    """Exact root paths normalize, while unrelated paths are left alone."""
    patched_src = Path("/nix/store/demo-src")
    generated_cargo = Path("/tmp/build/Cargo.nix")
    root_relative = os.path.relpath(patched_src, generated_cargo.parent).replace(
        os.sep,
        "/",
    )
    refreshed = (
        "        src = lib.cleanSourceWith { filter = sourceFilter;  "
        f"src = {root_relative}; }};\n"
        "        src = lib.cleanSourceWith { filter = sourceFilter;  "
        "src = ../vendor/demo; };\n"
    )

    stabilized = crate2nix._stabilize_generated_root_src_paths(
        refreshed,
        patched_src=patched_src,
        generated_cargo=generated_cargo,
    )

    assert 'src = "${rootSrc}"; };' in stabilized
    assert "src = ../vendor/demo; };" in stabilized


def test_resolve_targets_skips_unsupported_platforms(monkeypatch) -> None:
    """Default target selection should skip platform-specific packages."""
    monkeypatch.setattr(crate2nix, "_current_platform", lambda: "linux")

    runnable, skipped = crate2nix._resolve_targets(())

    assert [target.name for target in runnable] == [
        "codex",
        "goose-cli",
        "zed-editor-nightly",
    ]
    assert skipped == ["opencode-desktop"]


def test_stream_crate2nix_artifact_updates_emits_changed_artifacts(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Surface crate2nix regen through normal updater status/artifact events."""
    target = crate2nix.Crate2NixTarget(
        name="demo",
        patched_src_installable="path:.#demo-crate2nix-src",
        cargo_nix=Path("packages/demo/Cargo.nix"),
        crate_hashes=Path("packages/demo/crate-hashes.json"),
        normalizer_path=Path("packages/demo/normalize_cargo_nix.py"),
        supported_platforms=("linux",),
    )
    monkeypatch.setitem(crate2nix.TARGETS, "demo", target)
    monkeypatch.setattr(crate2nix, "_current_platform", lambda: "linux")
    monkeypatch.setattr(
        crate2nix,
        "_refresh_target",
        lambda _target: crate2nix.RefreshResult(
            cargo_nix="{ demo = true; }\n",
            crate_hashes='{"demo": "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="}\n',
        ),
    )

    async def _collect() -> list[UpdateEvent]:
        return [
            event async for event in crate2nix.stream_crate2nix_artifact_updates("demo")
        ]

    events = asyncio.run(_collect())

    assert [event.kind for event in events] == [
        UpdateEventKind.STATUS,
        UpdateEventKind.ARTIFACT,
        UpdateEventKind.STATUS,
    ]
    assert events[0].message == "Refreshing crate2nix artifacts..."
    assert events[2].message == "Prepared crate2nix artifacts"
    artifact_paths = tuple(
        str(artifact.path) for artifact in expect_artifact_updates(events[1].payload)
    )
    assert artifact_paths == (
        "packages/demo/Cargo.nix",
        "packages/demo/crate-hashes.json",
    )


def test_crate2nix_artifact_updates_skip_unknown_or_unsupported_targets(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Skip crate2nix refreshes for unknown names and unsupported platforms."""
    target = crate2nix.Crate2NixTarget(
        name="demo-skip",
        patched_src_installable="path:.#demo-skip-crate2nix-src",
        cargo_nix=Path("packages/demo/Cargo.nix"),
        crate_hashes=Path("packages/demo/crate-hashes.json"),
        normalizer_path=Path("packages/demo/normalize_cargo_nix.py"),
        supported_platforms=("linux",),
    )
    monkeypatch.setitem(crate2nix.TARGETS, "demo-skip", target)
    monkeypatch.setattr(crate2nix, "_current_platform", lambda: "darwin")
    monkeypatch.setattr(
        crate2nix,
        "_refresh_target",
        lambda _target: (_ for _ in ()).throw(AssertionError("should not refresh")),
    )

    assert crate2nix.crate2nix_artifact_updates("missing-target") == ()
    assert crate2nix.crate2nix_artifact_updates("demo-skip") == ()


def test_stream_crate2nix_artifact_updates_skips_unknown_or_unsupported_targets(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Do not emit events when the target is missing or unsupported here."""
    target = crate2nix.Crate2NixTarget(
        name="demo-stream-skip",
        patched_src_installable="path:.#demo-stream-skip-crate2nix-src",
        cargo_nix=Path("packages/demo/Cargo.nix"),
        crate_hashes=Path("packages/demo/crate-hashes.json"),
        normalizer_path=Path("packages/demo/normalize_cargo_nix.py"),
        supported_platforms=("linux",),
    )
    monkeypatch.setitem(crate2nix.TARGETS, "demo-stream-skip", target)
    monkeypatch.setattr(crate2nix, "_current_platform", lambda: "darwin")

    async def _collect(name: str) -> list[UpdateEvent]:
        return [
            event async for event in crate2nix.stream_crate2nix_artifact_updates(name)
        ]

    assert asyncio.run(_collect("missing-target")) == []
    assert asyncio.run(_collect("demo-stream-skip")) == []


def test_stream_crate2nix_artifact_updates_reports_up_to_date(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Emit an up-to-date status when regenerated artifacts are unchanged."""
    monkeypatch.setattr(crate2nix, "_current_platform", lambda: "linux")

    async def _to_thread(_func, _name: str) -> tuple[()]:
        return ()

    monkeypatch.setattr(crate2nix.asyncio, "to_thread", _to_thread)

    async def _collect() -> list[UpdateEvent]:
        return [
            event
            async for event in crate2nix.stream_crate2nix_artifact_updates("codex")
        ]

    events = asyncio.run(_collect())

    assert [event.kind for event in events] == [
        UpdateEventKind.STATUS,
        UpdateEventKind.STATUS,
    ]
    assert events[1].message == "crate2nix artifacts up to date"
    assert events[1].payload == {
        "status": "up_to_date",
        "operation": "materialize_artifacts",
        "detail": {"scope": "artifacts", "value": "crate2nix artifacts"},
    }


def test_targets_use_dedicated_source_installables() -> None:
    """Built-in targets should avoid final-package passthru source paths."""
    assert {
        name: target.patched_src_installable
        for name, target in crate2nix.TARGETS.items()
    } == {
        "codex": "path:.#codex-crate2nix-src",
        "goose-cli": "path:.#goose-cli-crate2nix-src",
        "zed-editor-nightly": "path:.#zed-editor-nightly-crate2nix-src",
        "opencode-desktop": "path:.#opencode-desktop-crate2nix-src",
    }


def test_crate2nix_source_installables_are_wired_through_package_registry() -> None:
    """Package registry contracts should expose crate2nix companions structurally."""
    packages_root = (crate2nix.REPO_ROOT / "packages").resolve()
    companion_entries = {
        f"{path.parent.name}-crate2nix-src"
        for path in packages_root.glob("*/crate2nix-src.nix")
    }
    expected_companions = {
        "codex-crate2nix-src",
        "goose-cli-crate2nix-src",
        "opencode-desktop-crate2nix-src",
        "zed-editor-nightly-crate2nix-src",
    }

    assert expected_companions <= companion_entries

    assert_nix_ast_equal(
        expect_scope_binding(_registry_expr(), "companionPackages").value,
        """
        discovery.discoverCompanionEntries {
          root = pkgDir;
          directories = discoveredPackages.dirNames;
          fileName = "crate2nix-src.nix";
        }
        """,
    )
    assert_nix_ast_equal(
        expect_scope_binding(_registry_expr(), "supportsSystem").value,
        """
        constraint: system:
        if constraint == null then
          true
        else if builtins.isList constraint then
          builtins.elem system constraint
        else if constraint == "darwin" then
          builtins.match ".*-darwin" system != null
        else
          throw "packages/registry.nix: unsupported system constraint `${constraint}`"
        """,
    )
    assert_nix_ast_equal(
        expect_binding(_registry_expr().values, "forSystem").value,
        "system: packagePathsMatching (meta: supportsSystem meta.constraint system)",
    )

    overrides = _registry_overrides()
    assert {name for name, meta in overrides.items() if meta.get("helper") is True} == {
        "go-cli-wrapper",
        "openchamber-bun",
        "registry",
        "t3code-workspace",
    }
    assert sorted(
        name for name, meta in overrides.items() if meta.get("constraint") == "darwin"
    ) == [
        "codex-desktop",
        "commander",
        "conductor",
        "granola",
        "netnewswire",
        "opencode-desktop-crate2nix-src",
        "raycast",
        "wispr-flow",
    ]
    assert overrides["sculptor"]["constraint"] == [
        "aarch64-darwin",
        "x86_64-darwin",
        "x86_64-linux",
    ]

    selected_paths = {
        "codex": str(packages_root / "codex/crate2nix-src.nix"),
        "goose": str(packages_root / "goose-cli/crate2nix-src.nix"),
        "opencode": str(packages_root / "opencode-desktop/crate2nix-src.nix"),
        "zed": str(packages_root / "zed-editor-nightly/crate2nix-src.nix"),
    }
    assert all(Path(path).is_file() for path in selected_paths.values())

    presence = {
        "gooseCli": {"linux": True, "darwin": True, "linuxAarch64": False},
        "gooseCliCrate2nixSrc": {
            "linux": True,
            "darwin": True,
            "linuxAarch64": True,
        },
        "codexCrate2nixSrc": {
            "linux": True,
            "darwin": True,
            "linuxAarch64": True,
        },
        "opencodeDesktopCrate2nixSrc": {
            "linux": False,
            "darwin": True,
            "linuxAarch64": False,
        },
        "zedEditorNightly": {
            "linux": True,
            "darwin": True,
            "linuxAarch64": False,
        },
        "zedEditorNightlyCrate2nixSrc": {
            "linux": True,
            "darwin": True,
            "linuxAarch64": False,
        },
        "sculptor": {
            "linux": True,
            "darwin": True,
            "x86Darwin": True,
            "linuxAarch64": False,
        },
    }
    systems = {
        "linux": "x86_64-linux",
        "darwin": "aarch64-darwin",
        "x86Darwin": "x86_64-darwin",
        "linuxAarch64": "aarch64-linux",
    }
    package_constraints = {
        name: overrides.get(name, {}).get("constraint")
        for name in (
            "goose-cli",
            "goose-cli-crate2nix-src",
            "codex-crate2nix-src",
            "opencode-desktop-crate2nix-src",
            "zed-editor-nightly",
            "zed-editor-nightly-crate2nix-src",
            "sculptor",
        )
    }
    assert {
        key: {
            surface: _supports_system(package_constraints[name], system)
            for surface, system in systems.items()
            if not (key != "sculptor" and surface == "x86Darwin")
        }
        for key, name in {
            "gooseCli": "goose-cli",
            "gooseCliCrate2nixSrc": "goose-cli-crate2nix-src",
            "codexCrate2nixSrc": "codex-crate2nix-src",
            "opencodeDesktopCrate2nixSrc": "opencode-desktop-crate2nix-src",
            "zedEditorNightly": "zed-editor-nightly",
            "zedEditorNightlyCrate2nixSrc": "zed-editor-nightly-crate2nix-src",
            "sculptor": "sculptor",
        }.items()
    } == presence


def test_run_writes_refreshed_files(monkeypatch, tmp_path: Path) -> None:
    """Write mode should persist refreshed Cargo.nix and crate-hashes.json."""
    target = crate2nix.Crate2NixTarget(
        name="demo",
        patched_src_installable="path:.#demo-crate2nix-src",
        cargo_nix=Path("demo/Cargo.nix"),
        crate_hashes=Path("demo/crate-hashes.json"),
        normalizer_path=Path("demo/normalize.py"),
        supported_platforms=("linux",),
    )
    demo_dir = tmp_path / "demo"
    demo_dir.mkdir()
    (demo_dir / "Cargo.nix").write_text("old cargo\n", encoding="utf-8")
    (demo_dir / "crate-hashes.json").write_text('{"old": 1}\n', encoding="utf-8")

    monkeypatch.setattr(crate2nix, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(crate2nix, "TARGETS", {"demo": target})
    monkeypatch.setattr(crate2nix, "_current_platform", lambda: "linux")
    monkeypatch.setattr(
        crate2nix,
        "_refresh_target",
        lambda _target: crate2nix.RefreshResult(
            cargo_nix="new cargo\n",
            crate_hashes='{"new": 2}\n',
        ),
    )

    rc = crate2nix.run(packages=("demo",), write=True)

    assert rc == 0
    assert (demo_dir / "Cargo.nix").read_text(encoding="utf-8") == "new cargo\n"
    assert (demo_dir / "crate-hashes.json").read_text(
        encoding="utf-8"
    ) == '{"new": 2}\n'


def test_run_fails_when_drift_is_detected(monkeypatch, tmp_path: Path) -> None:
    """Check mode should fail when refreshed artifacts differ."""
    target = crate2nix.Crate2NixTarget(
        name="demo",
        patched_src_installable="path:.#demo-crate2nix-src",
        cargo_nix=Path("demo/Cargo.nix"),
        crate_hashes=Path("demo/crate-hashes.json"),
        normalizer_path=Path("demo/normalize.py"),
        supported_platforms=("linux",),
    )
    demo_dir = tmp_path / "demo"
    demo_dir.mkdir()
    (demo_dir / "Cargo.nix").write_text("old cargo\n", encoding="utf-8")
    (demo_dir / "crate-hashes.json").write_text('{"old": 1}\n', encoding="utf-8")

    monkeypatch.setattr(crate2nix, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(crate2nix, "TARGETS", {"demo": target})
    monkeypatch.setattr(crate2nix, "_current_platform", lambda: "linux")
    monkeypatch.setattr(
        crate2nix,
        "_refresh_target",
        lambda _target: crate2nix.RefreshResult(
            cargo_nix="new cargo\n",
            crate_hashes='{"new": 2}\n',
        ),
    )

    rc = crate2nix.run(packages=("demo",), write=False)

    assert rc == 1
    assert (demo_dir / "Cargo.nix").read_text(encoding="utf-8") == "old cargo\n"


def test_current_platform_normalizes_known_systems(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Map platform.system() values to crate2nix platform names."""
    monkeypatch.setattr(crate2nix.platform, "system", lambda: "Darwin")
    assert crate2nix._current_platform() == "darwin"
    monkeypatch.setattr(crate2nix.platform, "system", lambda: "Linux")
    assert crate2nix._current_platform() == "linux"
    monkeypatch.setattr(crate2nix.platform, "system", lambda: "Plan9")
    assert crate2nix._current_platform() == "plan9"


def test_load_normalizer_handles_success_and_type_errors(tmp_path: Path) -> None:
    """Load normalizer modules and validate their callable contract."""
    good = tmp_path / "good.py"
    good.write_text(
        "def normalize(text):\n    return text + '! ', 1, True\n",
        encoding="utf-8",
    )
    normalize = crate2nix._load_normalizer(good)
    assert normalize("demo") == ("demo! ", 1, True)

    missing = tmp_path / "missing.py"
    missing.write_text("VALUE = 1\n", encoding="utf-8")
    with pytest.raises(TypeError, match="does not expose normalize"):
        crate2nix._load_normalizer(missing)

    invalid = tmp_path / "invalid.py"
    invalid.write_text(
        "def normalize(text):\n    return text\n",
        encoding="utf-8",
    )
    with pytest.raises(TypeError, match="returned an invalid result"):
        crate2nix._load_normalizer(invalid)("demo")


def test_load_normalizer_rejects_missing_spec(monkeypatch: pytest.MonkeyPatch) -> None:
    """Fail clearly when the normalizer helper module cannot be loaded."""
    monkeypatch.setattr(
        crate2nix,
        "load_module_from_path",
        lambda *_a, **_k: (_ for _ in ()).throw(RuntimeError("boom")),
    )
    with pytest.raises(RuntimeError, match="Could not load normalizer"):
        crate2nix._load_normalizer(Path("missing.py"))


def test_run_helper_and_build_patched_src_error_paths(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Surface subprocess failures and empty nix build output."""
    seen_env: dict[str, str] = {}

    def _success(
        _args: list[str],
        *,
        cwd: Path,
        env: dict[str, str] | None,
        text: bool,
        capture_output: bool,
        check: bool,
    ) -> subprocess.CompletedProcess[str]:
        del cwd, text, capture_output, check
        if env is not None:
            seen_env["FLAG"] = env["FLAG"]
        return subprocess.CompletedProcess(["cmd"], 0, stdout="ok\n", stderr="")

    monkeypatch.setattr(crate2nix.subprocess, "run", _success)
    assert crate2nix._run(["cmd"], env={"FLAG": "1"}).stdout == "ok\n"
    assert seen_env == {"FLAG": "1"}

    def _failure(
        _args: list[str],
        *,
        cwd: Path,
        env: dict[str, str] | None,
        text: bool,
        capture_output: bool,
        check: bool,
    ) -> subprocess.CompletedProcess[str]:
        del cwd, env, text, capture_output, check
        return subprocess.CompletedProcess(["cmd"], 1, stdout="", stderr="boom")

    monkeypatch.setattr(crate2nix.subprocess, "run", _failure)
    with pytest.raises(RuntimeError, match="boom"):
        crate2nix._run(["cmd"])

    monkeypatch.setattr(
        crate2nix,
        "_run",
        lambda _args, cwd=crate2nix.REPO_ROOT: subprocess.CompletedProcess(
            ["nix"], 0, stdout="/tmp/demo\n", stderr=""
        ),
    )
    assert crate2nix._build_patched_src(
        crate2nix.Crate2NixTarget(
            name="demo",
            patched_src_installable="path:.#demo",
            cargo_nix=Path("Cargo.nix"),
            crate_hashes=Path("crate-hashes.json"),
            normalizer_path=Path("normalize.py"),
            supported_platforms=("linux",),
        )
    ) == Path("/tmp/demo")
    monkeypatch.setattr(
        crate2nix,
        "_run",
        lambda _args, cwd=crate2nix.REPO_ROOT: subprocess.CompletedProcess(
            ["nix"], 0, stdout="\n", stderr=""
        ),
    )
    with pytest.raises(RuntimeError, match="No patchedSrc output path returned"):
        crate2nix._build_patched_src(
            crate2nix.Crate2NixTarget(
                name="demo",
                patched_src_installable="path:.#demo",
                cargo_nix=Path("Cargo.nix"),
                crate_hashes=Path("crate-hashes.json"),
                normalizer_path=Path("normalize.py"),
                supported_platforms=("linux",),
            )
        )


def test_refresh_target_materializes_normalized_outputs(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Refresh should run crate2nix generation and normalize both outputs."""
    patched_src = tmp_path / "patched-src"
    patched_src.mkdir()
    (patched_src / "Cargo.toml").write_text(
        "[package]\nname = 'demo'\n", encoding="utf-8"
    )
    target = crate2nix.Crate2NixTarget(
        name="demo",
        patched_src_installable="path:.#demo",
        cargo_nix=Path("demo/Cargo.nix"),
        crate_hashes=Path("demo/crate-hashes.json"),
        normalizer_path=Path("demo/normalize.py"),
        supported_platforms=("linux",),
        cargo_manifest_relpath=Path("nested/Cargo.toml"),
    )
    monkeypatch.setattr(crate2nix, "_build_patched_src", lambda _target: patched_src)
    monkeypatch.setattr(
        crate2nix,
        "_load_normalizer",
        lambda _path: lambda text: (text.replace("raw", "normalized") + "\n", 2, True),
    )

    def _run(
        args: list[str],
        *,
        cwd: Path = crate2nix.REPO_ROOT,
        env: dict[str, str] | None = None,
    ):
        del cwd
        assert args[args.index("-f") + 1] == str(patched_src / "nested/Cargo.toml")
        assert env == {"CARGO_NET_GIT_FETCH_WITH_CLI": "true"}
        generated_cargo = Path(args[args.index("-o") + 1])
        generated_hashes = Path(args[args.index("-h") + 1])
        generated_cargo.write_text(
            "# This file was @generated by crate2nix 0.15.0 with the command:\n"
            '#   "generate" "-f" "./Cargo.toml" "-o" "/tmp/Cargo.nix" '
            '"-h" "/tmp/crate-hashes.json" "--default-features"\n'
            "# See https://github.com/kolloch/crate2nix for more info.\n"
            "raw cargo\n",
            encoding="utf-8",
        )
        generated_hashes.write_text('{"b": 1, "a": 2}\n', encoding="utf-8")
        return subprocess.CompletedProcess(args, 0, stdout="", stderr="")

    monkeypatch.setattr(crate2nix, "_run", _run)
    refreshed = crate2nix._refresh_target(target)
    assert (
        refreshed.cargo_nix
        == "# This file was @generated by crate2nix 0.15.0 with the command:\n"
        '#   "generate" "-f" "nested/Cargo.toml" "-o" "demo/Cargo.nix" '
        '"-h" "demo/crate-hashes.json" "--default-features"\n'
        "# See https://github.com/kolloch/crate2nix for more info.\n"
        "normalized cargo\n"
    )
    assert refreshed.crate_hashes == '{\n  "a": 2,\n  "b": 1\n}\n'


def test_resolve_targets_and_run_cover_remaining_control_flow(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Exercise unsupported, empty, failure, and success run branches."""
    assert crate2nix.run(packages=("missing",), write=False) == 1
    assert "Error: Unknown crate2nix target" in capsys.readouterr().err

    with pytest.raises(RuntimeError, match="Unknown crate2nix target"):
        crate2nix._resolve_targets(("missing",))

    target = crate2nix.Crate2NixTarget(
        name="demo",
        patched_src_installable="path:.#demo",
        cargo_nix=Path("demo/Cargo.nix"),
        crate_hashes=Path("demo/crate-hashes.json"),
        normalizer_path=Path("demo/normalize.py"),
        supported_platforms=("linux",),
    )
    demo_dir = tmp_path / "demo"
    demo_dir.mkdir()
    (demo_dir / "Cargo.nix").write_text("same\n", encoding="utf-8")
    (demo_dir / "crate-hashes.json").write_text('{\n  "a": 1\n}\n', encoding="utf-8")

    monkeypatch.setattr(crate2nix, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(crate2nix, "TARGETS", {"demo": target})

    monkeypatch.setattr(crate2nix, "_current_platform", lambda: "darwin")
    assert crate2nix.run(packages=("demo",), write=False) == 1
    assert "unsupported on this platform" in capsys.readouterr().err

    monkeypatch.setattr(crate2nix, "_current_platform", lambda: "darwin")
    monkeypatch.setattr(crate2nix, "TARGETS", {})
    assert crate2nix.run() == 0
    assert "No crate2nix targets are runnable" in capsys.readouterr().err

    monkeypatch.setattr(crate2nix, "TARGETS", {"demo": target})
    monkeypatch.setattr(crate2nix, "_current_platform", lambda: "linux")
    monkeypatch.setattr(
        crate2nix,
        "_refresh_target",
        lambda _target: (_ for _ in ()).throw(RuntimeError("boom")),
    )
    assert crate2nix.run() == 1
    assert "Skipping unsupported crate2nix targets" not in capsys.readouterr().err

    skipped_target = crate2nix.Crate2NixTarget(
        name="zed",
        patched_src_installable="path:.#zed",
        cargo_nix=Path("demo/Cargo.nix"),
        crate_hashes=Path("demo/crate-hashes.json"),
        normalizer_path=Path("demo/normalize.py"),
        supported_platforms=("darwin",),
    )
    monkeypatch.setattr(crate2nix, "TARGETS", {"demo": target, "zed": skipped_target})
    monkeypatch.setattr(
        crate2nix,
        "_refresh_target",
        lambda _target: crate2nix.RefreshResult(
            cargo_nix="same\n",
            crate_hashes='{\n  "a": 1\n}\n',
        ),
    )
    assert crate2nix.run() == 0
    assert (
        "Skipping unsupported crate2nix targets on this platform: zed"
        in capsys.readouterr().err
    )
    monkeypatch.setattr(crate2nix, "TARGETS", {"demo": target})
    monkeypatch.setattr(
        crate2nix,
        "_refresh_target",
        lambda _target: (_ for _ in ()).throw(RuntimeError("boom")),
    )
    assert crate2nix.run() == 1
    assert "FAIL demo: boom" in capsys.readouterr().err

    monkeypatch.setattr(
        crate2nix,
        "_refresh_target",
        lambda _target: crate2nix.RefreshResult(
            cargo_nix="same\n",
            crate_hashes='{\n  "a": 1\n}\n',
        ),
    )
    assert crate2nix.run() == 0
    assert (
        "All checked-in crate2nix artifacts are up to date." in capsys.readouterr().err
    )


def test_cli_callback_exits_with_run_status(monkeypatch: pytest.MonkeyPatch) -> None:
    """The Typer callback should forward arguments into run()."""
    import lib.update.ci.crate2nix as crate2nix_cli

    called: dict[str, object] = {}

    def _fake_run(*, packages: tuple[str, ...] = (), write: bool = False) -> int:
        called["packages"] = packages
        called["write"] = write
        return 7

    monkeypatch.setattr(crate2nix_cli, "run", _fake_run)
    assert crate2nix_cli.main(["--package", "demo", "--write"]) == 7
    assert called == {"packages": ("demo",), "write": True}
