"""Typed definitions of this repo's generated GitHub Actions workflows.

The committed files ``.github/workflows/update.yml``, ``ci.yml``, and
``update-certify.yml`` are generated artifacts rendered from the models in
this module via ``nixcfg ci workflow generate`` and drift-checked via
``nixcfg ci workflow verify-generated``. Structural invariants (artifact
upload/download naming, needs-graph consistency) are enforced at render time
by :meth:`lib.update.ci.workflow_model.Workflow.validate_structure`; shared
values such as the Darwin heavy-target split and quality-check lists are
consistent by construction because they are built from single Python
constants below.

``update-self-heal.md`` / ``update-self-heal.lock.yml`` are compiled by the
external ``gh-aw`` tool and are intentionally not managed here.
"""

from __future__ import annotations

from lib.update.ci.update_target_artifacts import REFRESH_FINAL_ARTIFACT_ALLOWED_SPECS
from lib.update.ci.workflow_model import (
    Concurrency,
    Job,
    Matrix,
    ScalarValue,
    Step,
    Strategy,
    Triggers,
    Workflow,
    WorkflowCallInput,
    WorkflowCallTrigger,
)

GENERATED_WORKFLOW_HEADER_COMMENTS = (
    "Generated by `nixcfg ci workflow generate` -- do not hand-edit.",
    "Source of truth: lib/update/ci/workflow_defs.py.",
)

UPDATE_WORKFLOW_PATH = ".github/workflows/update.yml"
CI_WORKFLOW_PATH = ".github/workflows/ci.yml"
UPDATE_CERTIFY_WORKFLOW_PATH = ".github/workflows/update-certify.yml"

_CACHIX_NAME = "gkze"
_UPDATE_TOKEN = "${{ secrets.UPDATE_SELF_HEAL_GITHUB_TOKEN }}"
_TRIGGERS_DISABLED_COMMENT = (
    "Disabled: keep the workflow valid without automatic or manual triggers."
)

_CHECKOUT_USES = "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
_CHECKOUT_VERSION = "v4.2.2"
_SETUP_NIX_USES = (
    "DeterminateSystems/determinate-nix-action@a18f73c54ca8525de051e73c31512a67f44df919"
)
_CACHIX_USES = "cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1"
_CACHIX_VERSION = "v16"
_CACHE_USES = "actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7"
_CACHE_VERSION = "v5.0.4"
_UPLOAD_USES = "actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f"
_UPLOAD_VERSION = "v6.0.0"
_DOWNLOAD_USES = "actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131"
_DOWNLOAD_VERSION = "v7.0.0"
_SETUP_UV_USES = "astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78"
_SETUP_UV_VERSION = "v7.6.0"
_CREATE_PR_USES = (
    "peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0"
)
_CREATE_PR_VERSION = "v8.1.0"


def _script(*items: str) -> str:
    """Join literal lines into one block-scalar value without a final newline."""
    return "\n".join(items)


def _lines(*items: str) -> str:
    """Join literal lines into one block-scalar value with a final newline."""
    return _script(*items) + "\n"


_NIX_CACHE_PATH = _lines(
    "~/.cache/nix/tarball-cache",
    "~/.cache/nix/tarball-cache-v2",
)
_NIX_CACHE_RESTORE_KEYS = _lines(
    "nix-cache-${{ runner.os }}-${{ runner.arch }}-",
    "nix-cache-${{ runner.os }}-",
)
_NIX_CACHE_COMMENTS = (
    "Cache immutable tarball fetch artifacts only. Nix recreates",
    "mutable SQLite metadata caches locally, and persisting them via",
    "archive-based CI caches can restore malformed databases.",
)

_UPDATE_HASH_FILES = (
    "flake.lock",
    "packages/**/sources.json",
    "overlays/**/sources.json",
    "packages/**/uv.lock",
    "packages/**/deno-deps.json",
    "packages/**/build.zig.zon.nix",
    "packages/**/Cargo.nix",
    "packages/**/crate-hashes.json",
    "overlays/**/Cargo.nix",
    "overlays/**/crate-hashes.json",
    "packages/superset/bun.nix",
    "packages/superset/bun.lock",
    "packages/t3code/bun.lock",
    "packages/t3code-desktop/bun.lock",
)
_CERTIFY_HASH_FILES = _UPDATE_HASH_FILES[:-2]
_CI_HASH_FILES = (
    "flake.lock",
    "packages/**/sources.json",
    "overlays/**/sources.json",
    "packages/**/Cargo.nix",
    "packages/**/crate-hashes.json",
    "overlays/**/Cargo.nix",
    "overlays/**/crate-hashes.json",
    "packages/superset/bun.nix",
    "packages/superset/bun.lock",
    "packages/t3code/bun.lock",
    "packages/t3code-desktop/bun.lock",
)

# The refresh PR artifact contents are shared with the aggregation helper so
# workflow uploads and Python-side artifact handling cannot drift apart.
_MERGED_GENERATED_PATHS = _lines(*REFRESH_FINAL_ARTIFACT_ALLOWED_SPECS)
_MERGED_SOURCES_PATHS = _lines(*REFRESH_FINAL_ARTIFACT_ALLOWED_SPECS[:10])

_UPDATE_PLATFORMS = ("aarch64-darwin", "x86_64-linux", "aarch64-linux")


def _hash_files_key(files: tuple[str, ...]) -> str:
    """Build one tarball-cache key over hashed lockfile inputs."""
    quoted = ", ".join(f"'{name}'" for name in files)
    return (
        "nix-cache-${{ runner.os }}-${{ runner.arch }}-"
        "${{ hashFiles( " + quoted + " ) }}"
    )


_FLAKE_LOCK_ONLY_KEY = (
    "nix-cache-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('flake.lock') }}"
)


# ---------------------------------------------------------------------------
# Shared step factories
# ---------------------------------------------------------------------------


def _checkout_step(
    *,
    fetch_depth: int | None = None,
    token: str | None = _UPDATE_TOKEN,
    ref: str | None = None,
) -> Step:
    """Build one actions/checkout step."""
    with_: dict[str, str | int | bool] = {}
    if fetch_depth is not None:
        with_["fetch-depth"] = fetch_depth
    with_["persist-credentials"] = False
    if token is not None:
        with_["token"] = token
    if ref is not None:
        with_["ref"] = ref
    return Step(
        uses=_CHECKOUT_USES,
        uses_comment=_CHECKOUT_VERSION,
        with_=with_,
    )


def _setup_nix_step() -> Step:
    """Build the pinned Determinate Nix installer step."""
    return Step(
        comment_lines=(
            "Determinate Nix v3.17.1",
            "Nix uses this token for external api.github.com flake fetches.",
            'The default github.token produces HTTP 401 "Bad credentials" there.',
        ),
        uses=_SETUP_NIX_USES,
        with_={"github-token": _UPDATE_TOKEN},
    )


def _cachix_step(
    *,
    if_: str | None = None,
    push: bool = True,
    comment_lines: tuple[str, ...] = (),
) -> Step:
    """Build one cachix/cachix-action step."""
    with_: dict[str, str | int | bool] = {"name": "${{ env.CACHIX_NAME }}"}
    if push:
        with_["authToken"] = "${{ secrets.CACHIX_AUTH_TOKEN }}"
    with_["extraPullNames"] = "zed"
    if push:
        with_["useDaemon"] = True
    else:
        with_["skipPush"] = True
    return Step(
        comment_lines=comment_lines,
        if_=if_,
        uses=_CACHIX_USES,
        uses_comment=_CACHIX_VERSION,
        with_=with_,
    )


def _nix_cache_step(
    *,
    key: str,
    comment_lines: tuple[str, ...] = _NIX_CACHE_COMMENTS,
) -> Step:
    """Build one tarball-cache actions/cache step."""
    return Step(
        comment_lines=comment_lines,
        uses=_CACHE_USES,
        uses_comment=_CACHE_VERSION,
        with_={
            "path": _NIX_CACHE_PATH,
            "key": key,
            "restore-keys": _NIX_CACHE_RESTORE_KEYS,
        },
    )


def _upload_step(
    *,
    name: str,
    path: str,
    if_no_files_found: str = "error",
    if_: str | None = None,
) -> Step:
    """Build one actions/upload-artifact step."""
    return Step(
        if_=if_,
        uses=_UPLOAD_USES,
        uses_comment=_UPLOAD_VERSION,
        with_={"name": name, "if-no-files-found": if_no_files_found, "path": path},
    )


def _download_step(
    *,
    name: str | None = None,
    pattern: str | None = None,
    path: str,
    step_name: str | None = None,
    step_id: str | None = None,
    if_: str | None = None,
    continue_on_error: bool | None = None,
    comment_lines: tuple[str, ...] = (),
) -> Step:
    """Build one actions/download-artifact step."""
    with_: dict[str, str | int | bool] = {}
    if name is not None:
        with_["name"] = name
    if pattern is not None:
        with_["pattern"] = pattern
    with_["path"] = path
    return Step(
        comment_lines=comment_lines,
        name=step_name,
        id=step_id,
        if_=if_,
        continue_on_error=continue_on_error,
        uses=_DOWNLOAD_USES,
        uses_comment=_DOWNLOAD_VERSION,
        with_=with_,
    )


def _download_flake_lock_step() -> Step:
    """Download the refreshed flake.lock artifact into the workspace."""
    return _download_step(name="flake-lock", path=".")


def _setup_uv_step() -> Step:
    """Build the pinned astral-sh/setup-uv step."""
    return Step(
        uses=_SETUP_UV_USES,
        uses_comment=_SETUP_UV_VERSION,
        with_={"enable-cache": True, "ignore-nothing-to-cache": True},
    )


def _free_disk_space_step(*, if_: str | None = None) -> Step:
    """Build the CI runner disk-cleanup step."""
    return Step(
        name="Free disk space",
        if_=if_,
        run="nix run .#nixcfg -- ci workflow free-disk-space",
    )


def _prefetch_flake_inputs_step() -> Step:
    """Build the flake input prefetch step."""
    return Step(
        name="Pre-fetch flake inputs",
        run="nix run .#nixcfg -- ci workflow prefetch-flake-inputs",
    )


def _tarball_checkout_step(
    *, step_name: str, ref_expression: str, env: dict[str, str]
) -> Step:
    """Build the tarball-based checkout used on hosted arm64 Linux runners."""
    return Step(
        name=step_name,
        env=env,
        run=_lines(
            "set -euo pipefail",
            'tmp_dir="$(mktemp -d)"',
            "trap 'rm -rf \"$tmp_dir\"' EXIT",
            "curl --fail --location --location-trusted --silent --show-error \\",
            '  --header "Authorization: Bearer ${GITHUB_TOKEN}" \\',
            '  --header "X-GitHub-Api-Version: 2022-11-28" \\',
            '  --output "$tmp_dir/repo.tar.gz" \\',
            '  "${GITHUB_API_URL:-https://api.github.com}/repos/'
            "${GITHUB_REPOSITORY}/tarball/" + ref_expression + '"',
            'tar -xzf "$tmp_dir/repo.tar.gz" --strip-components=1',
            "git init -q",
            "git config user.name github-actions",
            "git config user.email github-actions@github.com",
            "git add -A",
            'git commit -q -m "workspace snapshot"',
        ),
    )


# ---------------------------------------------------------------------------
# Shared quality-check inventory (also consumed by the CI quality matrix)
# ---------------------------------------------------------------------------

FAST_QUALITY_CHECKS = (
    "format-repo",
    "lint-editorconfig",
    "format-yaml-yamlfmt",
    "lint-yaml-yamllint",
    "format-web-oxfmt",
    "lint-web-oxlint",
    "format-python-pyupgrade",
    "format-python-ruff",
    "lint-python-compile",
    "lint-python-ruff",
    "lint-python-ty",
    "lint-workflows-actionlint",
)
DEEP_QUALITY_CHECKS = (
    "test-nix-default-api",
    "test-nix-package-helpers",
    "test-nix-opencode-desktop",
    "cache-electron-runtimes",
    "test-python-pytest",
    "verify-workflow-generated",
)


def _nix_check_builds(checks: tuple[str, ...]) -> str:
    """Build one run block that builds each named flake check."""
    return _lines(*(f"nix build .#checks.x86_64-linux.{check}" for check in checks))


# ---------------------------------------------------------------------------
# Update refresh workflow (.github/workflows/update.yml)
# ---------------------------------------------------------------------------


def _update_lock_job() -> Job:
    """Phase 1: refresh flake.lock and superset lock artifacts."""
    return Job(
        comment_lines=("Phase 1: Update flake.lock",),
        runs_on="ubuntu-24.04",
        timeout_minutes=30,
        steps=(
            _checkout_step(),
            _setup_nix_step(),
            _cachix_step(
                comment_lines=(
                    "Push store paths incrementally as each build completes while also",
                    "pulling from the public zed cache.",
                ),
            ),
            _nix_cache_step(key=_hash_files_key(_UPDATE_HASH_FILES)),
            Step(
                name="Verify generated workflow files are fresh",
                run="nix run .#nixcfg -- ci workflow verify-generated",
            ),
            Step(
                name="Snapshot superset flake input",
                run=(
                    "nix run .#nixcfg -- ci workflow flake-input snapshot "
                    "--node superset --output /tmp/superset-lock-before.json"
                ),
            ),
            Step(run="nix run .#nixcfg -- ci workflow nix-flake-update"),
            Step(
                name="Detect superset flake input changes",
                id="superset-changed",
                run=(
                    "nix run .#nixcfg -- ci workflow flake-input compare "
                    "--node superset --before /tmp/superset-lock-before.json "
                    '--github-output "$GITHUB_OUTPUT"'
                ),
            ),
            Step(
                name="Regenerate superset bun2nix lock",
                if_="steps.superset-changed.outputs.changed == 'true'",
                run="nix run .#superset.passthru.updateScript",
            ),
            Step(
                name="Format regenerated superset bun.nix",
                if_="steps.superset-changed.outputs.changed == 'true'",
                run="nix fmt -- packages/superset/bun.nix",
            ),
            _upload_step(
                name="flake-lock",
                path=_lines(
                    "flake.lock",
                    "packages/superset/bun.nix",
                    "packages/superset/bun.lock",
                ),
            ),
        ),
    )


def _darwin_lock_smoke_job() -> Job:
    """Phase 2: lock-only Darwin smoke evaluation."""
    return Job(
        comment_lines=(
            "Phase 2: Catch lock-only Darwin input breakage immediately "
            "after flake.lock refresh",
        ),
        needs=("update-lock",),
        runs_on="macos-15",
        timeout_minutes=30,
        steps=(
            _checkout_step(),
            _setup_nix_step(),
            _cachix_step(),
            _download_flake_lock_step(),
            _nix_cache_step(key=_hash_files_key(_UPDATE_HASH_FILES)),
            _prefetch_flake_inputs_step(),
            Step(
                name="Evaluate lock-only Darwin smoke expressions",
                run="nix run .#nixcfg -- ci workflow darwin eval-lock-smoke",
            ),
        ),
    )


def _resolve_versions_job() -> Job:
    """Phase 3: resolve upstream versions once."""
    return Job(
        comment_lines=(
            "Phase 3: Resolve upstream versions once (eliminates cross-platform race)",
        ),
        needs=("update-lock",),
        runs_on="ubuntu-24.04",
        timeout_minutes=20,
        steps=(
            _checkout_step(),
            _setup_nix_step(),
            _cachix_step(),
            _download_flake_lock_step(),
            _nix_cache_step(key=_hash_files_key(_UPDATE_HASH_FILES)),
            Step(
                name="Resolve upstream versions",
                env={"GITHUB_TOKEN": _UPDATE_TOKEN},
                run=(
                    "nix run .#nixcfg -- ci pipeline versions "
                    "--output pinned-versions.json"
                ),
            ),
            _upload_step(name="pinned-versions", path="pinned-versions.json"),
        ),
    )


def _discover_update_targets_job() -> Job:
    """Phase 4: discover the package update target matrix."""
    return Job(
        comment_lines=(
            "Phase 4: Discover package update targets once for "
            "package-sliced refresh jobs.",
        ),
        needs=("update-lock", "resolve-versions"),
        runs_on="ubuntu-24.04",
        timeout_minutes=15,
        outputs={"targets": "${{ steps.matrix.outputs.targets }}"},
        steps=(
            _checkout_step(),
            _setup_nix_step(),
            _cachix_step(),
            _download_flake_lock_step(),
            _nix_cache_step(key=_hash_files_key(_UPDATE_HASH_FILES)),
            Step(
                name="Build update target matrix",
                id="matrix",
                env={"GITHUB_TOKEN": _UPDATE_TOKEN},
                run=_lines(
                    "nix run .#nixcfg -- update --list --json > update-targets.json",
                    "python3 lib/update/ci/update_target_artifacts.py matrix \\",
                    "  --inventory update-targets.json \\",
                    "  --output update-target-matrix.json",
                    "{",
                    '  echo "targets<<EOF"',
                    "  cat update-target-matrix.json",
                    '  echo "EOF"',
                    '} >> "$GITHUB_OUTPUT"',
                ),
            ),
            _upload_step(
                name="update-target-matrix",
                path=_lines("update-targets.json", "update-target-matrix.json"),
            ),
        ),
    )


def _pinned_versions_download_steps() -> tuple[Step, Step]:
    """Build the pinned-versions download with one retry."""
    return (
        _download_step(
            step_name="Download pinned versions",
            step_id="download-pinned-versions",
            continue_on_error=True,
            name="pinned-versions",
            path=".",
        ),
        _download_step(
            step_name="Retry pinned versions artifact download",
            if_="steps.download-pinned-versions.outcome != 'success'",
            name="pinned-versions",
            path=".",
        ),
    )


def _stage_target_artifact_step(*, platform: str) -> Step:
    """Build the per-target artifact staging step for one platform."""
    matrix_key = f"artifact_paths_{platform.replace('-', '_')}"
    return Step(
        name="Stage target artifact",
        if_="always()",
        env={
            "ARTIFACT_PATHS_JSON": "${{ toJSON(matrix." + matrix_key + ") }}",
            "UPDATE_OUTCOME": "${{ steps.update-target.outcome }}",
        },
        run=_lines(
            "exit_code=1",
            'if [ "$UPDATE_OUTCOME" = "success" ]; then',
            "  exit_code=0",
            "fi",
            "python3 lib/update/ci/update_target_artifacts.py stage \\",
            "  --root . \\",
            "  --output update-target-artifact \\",
            '  --target "${{ matrix.target }}" \\',
            f"  --platform {platform} \\",
            '  --artifact-paths-json "$ARTIFACT_PATHS_JSON" \\',
            '  --exit-code "$exit_code"',
        ),
    )


_COMPUTE_HASHES_RUN_FOLDED = (
    "nix run .#nixcfg -- update --native-only "
    '--pinned-versions pinned-versions.json "${{ matrix.target }}"'
)
_COMPUTE_HASHES_RUN_BLOCK = _lines(
    "nix run .#nixcfg -- update --native-only \\",
    "  --pinned-versions pinned-versions.json \\",
    '  "${{ matrix.target }}"',
)


def _compute_hashes_job(*, platform: str) -> Job:
    """Phase 5: build one per-platform hash computation job."""
    is_darwin = platform == "aarch64-darwin"
    is_aarch64_linux = platform == "aarch64-linux"

    if is_aarch64_linux:
        checkout = _tarball_checkout_step(
            step_name="Check out repository archive",
            ref_expression="${GITHUB_SHA}",
            env={"GITHUB_TOKEN": _UPDATE_TOKEN},
        )
    else:
        checkout = _checkout_step()

    compute_env = {
        "GITHUB_TOKEN": _UPDATE_TOKEN,
        "UPDATE_SUBPROCESS_TIMEOUT": "14400",
    }
    if not is_aarch64_linux:
        compute_env["UPDATE_MAX_NIX_BUILDS"] = "1"

    darwin_only_steps = (
        (
            Step(
                name="Regenerate T3 Code runtime Bun locks",
                if_="matrix.regenerate_runtime_locks == true",
                run="nix run .#t3code-desktop.passthru.updateRuntimeLocks",
            ),
        )
        if is_darwin
        else ()
    )

    return Job(
        comment_lines=(
            ("Phase 5: Compute package-specific hashes in parallel on native runners.",)
            if is_darwin
            else ()
        ),
        needs=(
            "update-lock",
            *(("darwin-lock-smoke",) if is_darwin else ()),
            "resolve-versions",
            "discover-update-targets",
        ),
        runs_on={
            "aarch64-darwin": "macos-15",
            "x86_64-linux": "ubuntu-24.04",
            "aarch64-linux": "ubuntu-24.04-arm",
        }[platform],
        name=platform + " / ${{ matrix.target }}",
        timeout_minutes=300,
        strategy=Strategy(
            fail_fast=False,
            max_parallel=16,
            matrix="${{ fromJSON(needs.discover-update-targets.outputs.targets) }}",
        ),
        steps=(
            checkout,
            _setup_nix_step(),
            _cachix_step(),
            _download_flake_lock_step(),
            _nix_cache_step(key=_FLAKE_LOCK_ONLY_KEY),
            *_pinned_versions_download_steps(),
            _free_disk_space_step(
                if_=(
                    "runner.os == 'Linux' || runner.os == 'macOS'"
                    if is_darwin
                    else None
                ),
            ),
            _setup_uv_step(),
            *darwin_only_steps,
            Step(
                comment_lines=(
                    (
                        "Run update with pinned versions to ensure all "
                        "platforms use the",
                        "same upstream version (resolved in the resolve-versions job).",
                    )
                    if is_darwin
                    else ()
                ),
                name=f"Compute hashes for ${{{{ matrix.target }}}} on {platform}",
                id="update-target",
                continue_on_error=True,
                env=compute_env,
                run=(
                    _COMPUTE_HASHES_RUN_BLOCK
                    if platform == "x86_64-linux"
                    else _COMPUTE_HASHES_RUN_FOLDED
                ),
            ),
            _stage_target_artifact_step(platform=platform),
            _upload_step(
                if_="always()",
                name=f"update-target-{platform}-${{{{ matrix.artifact_slug }}}}",
                path="update-target-artifact",
            ),
            Step(
                name="Fail target job if update failed",
                if_="steps.update-target.outcome != 'success'",
                run="exit 1",
            ),
        ),
    )


def _aggregate_platform_updates_job() -> Job:
    """Aggregate per-target artifacts into per-platform source sets."""
    return Job(
        needs=(
            "discover-update-targets",
            "compute-hashes-aarch64-darwin",
            "compute-hashes-x86_64-linux",
            "compute-hashes-aarch64-linux",
        ),
        if_=(
            "always() && !cancelled() && "
            "needs.discover-update-targets.result == 'success'"
        ),
        runs_on="ubuntu-24.04",
        name="aggregate / ${{ matrix.platform }}",
        timeout_minutes=30,
        strategy=Strategy(
            fail_fast=False,
            matrix=Matrix(
                include=tuple({"platform": platform} for platform in _UPDATE_PLATFORMS),
            ),
        ),
        steps=(
            _checkout_step(),
            _setup_nix_step(),
            _cachix_step(),
            _download_step(pattern="update-target-*", path="update-target-artifacts"),
            Step(
                name="Aggregate successful package artifacts",
                run=(
                    "python3 lib/update/ci/update_target_artifacts.py aggregate "
                    "--artifacts-dir update-target-artifacts "
                    '--output "aggregated-${{ matrix.platform }}" '
                    '--platform "${{ matrix.platform }}"'
                ),
            ),
            _upload_step(
                name="sources-${{ matrix.platform }}",
                path=_lines(
                    "aggregated-${{ matrix.platform }}/packages/**/sources.json",
                    "aggregated-${{ matrix.platform }}/overlays/**/sources.json",
                    "aggregated-${{ matrix.platform }}"
                    "/nixcfg-update-target-status.json",
                ),
            ),
            _upload_step(
                if_="matrix.platform == 'x86_64-linux'",
                name="generated-artifacts-${{ matrix.platform }}",
                if_no_files_found="ignore",
                path=_lines(
                    "aggregated-${{ matrix.platform }}/packages/**/uv.lock",
                    "aggregated-${{ matrix.platform }}/packages/**/deno-deps.json",
                    "aggregated-${{ matrix.platform }}/packages/**/build.zig.zon.nix",
                ),
            ),
            _upload_step(
                if_="matrix.platform == 'aarch64-darwin'",
                name="generated-artifacts-${{ matrix.platform }}-runtime-locks",
                if_no_files_found="ignore",
                path=_lines(
                    "aggregated-${{ matrix.platform }}/packages/t3code/bun.lock",
                    "aggregated-${{ matrix.platform }}"
                    "/packages/t3code-desktop/bun.lock",
                ),
            ),
            _upload_step(
                name="update-target-status-${{ matrix.platform }}",
                path=(
                    "aggregated-${{ matrix.platform }}/nixcfg-update-target-status.json"
                ),
            ),
        ),
    )


def _merge_hashes_job() -> Job:
    """Phase 6: merge per-platform hashes into one source tree."""
    return Job(
        comment_lines=("Phase 6: Merge platform-specific hashes",),
        needs=("aggregate-platform-updates",),
        runs_on="ubuntu-24.04",
        timeout_minutes=30,
        steps=(
            _checkout_step(),
            _setup_nix_step(),
            _cachix_step(),
            _download_flake_lock_step(),
            _download_step(
                name="sources-aarch64-darwin", path="sources-aarch64-darwin"
            ),
            _download_step(name="sources-x86_64-linux", path="sources-x86_64-linux"),
            _download_step(name="sources-aarch64-linux", path="sources-aarch64-linux"),
            _download_step(
                step_name="Materialize checked-in generated updater artifacts",
                comment_lines=(
                    "These generated files are platform-independent metadata. "
                    "Download one",
                    "canonical artifact at the repository root so checked-in "
                    "lockfiles and",
                    "manifests are carried forward into merged-sources and "
                    "the PR branch.",
                ),
                continue_on_error=True,
                name="generated-artifacts-x86_64-linux",
                path="packages",
            ),
            _download_step(
                step_name="Materialize checked-in Darwin updater artifacts",
                continue_on_error=True,
                name="generated-artifacts-aarch64-darwin-runtime-locks",
                path="packages",
            ),
            _nix_cache_step(key=_hash_files_key(_UPDATE_HASH_FILES)),
            Step(
                name="Merge per-package sources files",
                run=_lines(
                    "nix run .#nixcfg -- ci pipeline sources \\",
                    "  sources-aarch64-darwin \\",
                    "  sources-x86_64-linux \\",
                    "  sources-aarch64-linux",
                ),
            ),
            _upload_step(name="merged-sources", path=_MERGED_SOURCES_PATHS),
        ),
    )


def _crate2nix_linux_job() -> Job:
    """Phase 7 (Linux): refresh crate2nix artifacts."""
    return Job(
        comment_lines=(
            "Phase 7: Refresh checked-in generated artifacts on native platforms",
        ),
        needs=("merge-hashes",),
        runs_on="ubuntu-24.04",
        timeout_minutes=45,
        steps=(
            _checkout_step(),
            _setup_nix_step(),
            _cachix_step(),
            _download_step(name="merged-sources", path="."),
            _nix_cache_step(key=_hash_files_key(_UPDATE_HASH_FILES)),
            Step(
                name="Refresh Linux crate2nix artifacts",
                run="nix run .#nixcfg -- ci pipeline crate2nix --write",
            ),
            _upload_step(
                name="crate2nix-linux",
                path=_lines(
                    "packages/**/Cargo.nix",
                    "packages/**/crate-hashes.json",
                    "overlays/**/Cargo.nix",
                    "overlays/**/crate-hashes.json",
                ),
            ),
        ),
    )


def _crate2nix_darwin_job() -> Job:
    """Phase 7 (Darwin): refresh zed-editor-nightly crate2nix artifacts."""
    return Job(
        needs=("merge-hashes",),
        runs_on="macos-15",
        timeout_minutes=120,
        steps=(
            _checkout_step(),
            _setup_nix_step(),
            _cachix_step(),
            _download_step(name="merged-sources", path="."),
            _nix_cache_step(key=_hash_files_key(_UPDATE_HASH_FILES)),
            _free_disk_space_step(),
            _prefetch_flake_inputs_step(),
            Step(
                name="Refresh Darwin crate2nix artifacts",
                run=(
                    "nix run .#nixcfg -- ci pipeline crate2nix --write "
                    "--package zed-editor-nightly"
                ),
            ),
            _upload_step(
                name="crate2nix-darwin",
                path=_lines(
                    "packages/zed-editor-nightly/Cargo.nix",
                    "packages/zed-editor-nightly/crate-hashes.json",
                ),
            ),
        ),
    )


def _merge_generated_job() -> Job:
    """Merge crate2nix artifacts with the merged source tree."""
    return Job(
        needs=("merge-hashes", "crate2nix-linux", "crate2nix-darwin"),
        runs_on="ubuntu-24.04",
        timeout_minutes=20,
        steps=(
            _checkout_step(),
            _download_step(name="merged-sources", path="."),
            _download_step(name="crate2nix-linux", path="."),
            _download_step(
                name="crate2nix-darwin",
                path="packages/zed-editor-nightly",
            ),
            _upload_step(name="merged-generated", path=_MERGED_GENERATED_PATHS),
        ),
    )


def _refresh_sanity_job() -> Job:
    """Phase 8: sanity checks over the merged update tree."""
    return Job(
        comment_lines=(
            "Phase 8: Refresh sanity checks required before opening the PR",
        ),
        needs=("merge-generated",),
        runs_on="ubuntu-24.04",
        timeout_minutes=30,
        steps=(
            _checkout_step(),
            _setup_nix_step(),
            _cachix_step(),
            _download_step(name="merged-generated", path="."),
            _nix_cache_step(key=_hash_files_key(_UPDATE_HASH_FILES)),
            Step(name="Check Nix formatting", run="nix fmt -- --ci"),
            Step(
                name="Verify crate2nix artifacts are fresh",
                run="nix run .#nixcfg -- ci pipeline crate2nix",
            ),
            Step(
                name="Validate update-target package derivations",
                run=("nix run .#nixcfg -- ci workflow validate-update-derivations"),
            ),
            Step(
                name="Smoke-check update app evaluation",
                run="nix run .#nixcfg -- ci workflow smoke-check-update-app",
            ),
            _upload_step(
                name="merged-generated-formatted",
                path=_MERGED_GENERATED_PATHS,
            ),
        ),
    )


def _validate_derivations_darwin_job() -> Job:
    """Validate Darwin update targets against the fully merged artifact tree."""
    return Job(
        comment_lines=(
            "Phase 8: Darwin derivation checks over the merged update tree",
        ),
        needs=("merge-generated",),
        runs_on="macos-15",
        timeout_minutes=30,
        steps=(
            _checkout_step(),
            _setup_nix_step(),
            _cachix_step(),
            _download_step(name="merged-generated", path="."),
            _nix_cache_step(key=_hash_files_key(_UPDATE_HASH_FILES)),
            _free_disk_space_step(),
            Step(
                name="Validate Darwin update-target package derivations",
                run=("nix run .#nixcfg -- ci workflow validate-update-derivations"),
            ),
        ),
    )


def _create_pr_job() -> Job:
    """Phase 9: open or refresh the update PR."""
    return Job(
        comment_lines=("Phase 9: Create PR with updates",),
        needs=(
            "merge-generated",
            "validate-derivations-darwin",
            "refresh-sanity",
        ),
        runs_on="ubuntu-24.04",
        timeout_minutes=30,
        permissions={
            "actions": "write",
            "contents": "write",
            "pull-requests": "write",
        },
        steps=(
            _checkout_step(),
            _setup_nix_step(),
            _cachix_step(),
            _download_step(name="merged-generated-formatted", path="."),
            _nix_cache_step(key=_hash_files_key(_UPDATE_HASH_FILES)),
            Step(
                comment_lines=("yamllint disable rule:line-length",),
                trailing_comment_lines=("yamllint enable rule:line-length",),
                name="Generate PR body",
                run=_lines(
                    "nix run .#nixcfg -- ci workflow generate-pr-body \\",
                    "  --output /tmp/pr-body.md \\",
                    "  --workflow-url \\",
                    '    "${{ github.server_url }}/${{ github.repository }}'
                    '/actions/runs/${{ github.run_id }}" \\',
                    '  --server-url "${{ github.server_url }}" \\',
                    '  --repository "${{ github.repository }}" \\',
                    '  --base-ref "${{ github.base_ref || '
                    'github.event.repository.default_branch }}"',
                ),
            ),
            Step(
                id="cpr",
                uses=_CREATE_PR_USES,
                uses_comment=_CREATE_PR_VERSION,
                with_={
                    "token": _UPDATE_TOKEN,
                    "sign-commits": True,
                    "branch": "update_flake_lock_action",
                    "delete-branch": True,
                    "title": "${{ env.UPDATE_COMMIT_MESSAGE }}",
                    "commit-message": "${{ env.UPDATE_COMMIT_MESSAGE }}",
                    "body-path": "/tmp/pr-body.md",
                },
            ),
            Step(
                name="Dispatch PR-head CI workflow",
                if_=(
                    "steps.cpr.outputs.pull-request-number != '' && "
                    "steps.cpr.outputs.pull-request-operation != 'closed'"
                ),
                env={
                    "GH_TOKEN": _UPDATE_TOKEN,
                    "UPDATE_BRANCH": "${{ steps.cpr.outputs.pull-request-branch }}",
                },
                run='gh workflow run ci.yml --ref "${UPDATE_BRANCH}"',
            ),
        ),
    )


def update_workflow() -> Workflow:
    """Build the update refresh workflow."""
    return Workflow(
        name="Update",
        env={
            "CACHIX_NAME": _CACHIX_NAME,
            "UPDATE_COMMIT_MESSAGE": (
                "chore: update flake.lock, sources, uv.lock, and crate2nix"
            ),
        },
        triggers=Triggers(comment_lines=(_TRIGGERS_DISABLED_COMMENT,)),
        concurrency=Concurrency(group="flake-update-refresh", cancel_in_progress=True),
        permissions={"contents": "read"},
        jobs={
            "update-lock": _update_lock_job(),
            "darwin-lock-smoke": _darwin_lock_smoke_job(),
            "resolve-versions": _resolve_versions_job(),
            "discover-update-targets": _discover_update_targets_job(),
            **{
                f"compute-hashes-{platform}": _compute_hashes_job(platform=platform)
                for platform in _UPDATE_PLATFORMS
            },
            "aggregate-platform-updates": _aggregate_platform_updates_job(),
            "merge-hashes": _merge_hashes_job(),
            "crate2nix-linux": _crate2nix_linux_job(),
            "crate2nix-darwin": _crate2nix_darwin_job(),
            "merge-generated": _merge_generated_job(),
            "validate-derivations-darwin": _validate_derivations_darwin_job(),
            "refresh-sanity": _refresh_sanity_job(),
            "create-pr": _create_pr_job(),
        },
    )


# ---------------------------------------------------------------------------
# CI workflow (.github/workflows/ci.yml)
# ---------------------------------------------------------------------------


def _ci_checkout_step() -> Step:
    """Build the CI checkout step (full history, default token)."""
    return _checkout_step(fetch_depth=0, token=None)


def _ci_cachix_steps() -> tuple[Step, Step]:
    """Build the default-branch push and PR read-only cachix steps."""
    default_branch = "format('refs/heads/{0}', github.event.repository.default_branch)"
    return (
        _cachix_step(
            if_=f"github.ref == {default_branch}",
            comment_lines=(
                "Push store paths incrementally as Nix finishes each build and pull",
                "from the public zed cache alongside our own cache.",
            ),
        ),
        _cachix_step(if_=f"github.ref != {default_branch}", push=False),
    )


def _ci_shared_steps() -> tuple[Step, ...]:
    """Build the shared CI job preamble."""
    return (
        _ci_checkout_step(),
        _setup_nix_step(),
        *_ci_cachix_steps(),
        _nix_cache_step(key=_hash_files_key(_CI_HASH_FILES)),
    )


def _commitlint_job() -> Job:
    """Lint commit messages over the pushed or PR commit range."""
    return Job(
        timeout_minutes=15,
        runs_on="ubuntu-24.04",
        steps=(
            *_ci_shared_steps(),
            Step(
                name="Lint commit messages",
                run=_script(
                    'case "${{ github.event_name }}" in',
                    "  pull_request)",
                    '    FROM="${{ github.event.pull_request.base.sha }}"',
                    '    TO="${{ github.event.pull_request.head.sha }}"',
                    "    ;;",
                    "  push)",
                    '    FROM="${{ github.event.before }}"',
                    '    TO="${{ github.sha }}"',
                    "    ;;",
                    "  *)",
                    '    FROM=""',
                    '    TO="${{ github.sha }}"',
                    "    ;;",
                    "esac",
                    "",
                    'if [ -n "$FROM" ] && '
                    '[ "$FROM" != "0000000000000000000000000000000000000000" ]; then',
                    "  nix run --inputs-from . nixpkgs#commitlint -- \\",
                    '    --from "$FROM" \\',
                    '    --to "$TO" \\',
                    "    --verbose",
                    "else",
                    "  nix run --inputs-from . nixpkgs#commitlint -- \\",
                    "    --last \\",
                    "    --verbose",
                    "fi",
                ),
            ),
        ),
    )


def _quality_job() -> Job:
    """Run each repo flake check as one matrix slice."""
    return Job(
        strategy=Strategy(
            fail_fast=False,
            matrix=Matrix(
                values={"check": (*FAST_QUALITY_CHECKS, *DEEP_QUALITY_CHECKS)},
            ),
        ),
        name="${{ matrix.check }}",
        runs_on="ubuntu-24.04",
        timeout_minutes=60,
        steps=(
            *_ci_shared_steps(),
            Step(
                name="Run quality gate",
                run="nix build .#checks.x86_64-linux.${{ matrix.check }}",
            ),
        ),
    )


def _lint_pins_pinact_job() -> Job:
    """Verify pinned action SHA annotations."""
    return Job(
        runs_on="ubuntu-24.04",
        timeout_minutes=30,
        steps=(
            *_ci_shared_steps(),
            Step(
                name="Verify pinned action annotations with pinact",
                env={"GITHUB_TOKEN": "${{ github.token }}"},
                run="nix run --inputs-from . nixpkgs#pinact -- run --check",
            ),
        ),
    )


def _verify_crate2nix_job() -> Job:
    """Verify committed crate2nix artifacts are fresh."""
    return Job(
        runs_on="ubuntu-24.04",
        timeout_minutes=60,
        steps=(
            *_ci_shared_steps(),
            Step(
                name="Verify crate2nix artifacts are fresh",
                run="nix run .#nixcfg -- ci pipeline crate2nix",
            ),
        ),
    )


def ci_workflow() -> Workflow:
    """Build the CI workflow."""
    return Workflow(
        name="CI",
        triggers=Triggers(comment_lines=(_TRIGGERS_DISABLED_COMMENT,)),
        concurrency=Concurrency(
            group=(
                "${{ github.workflow }}-"
                "${{ github.event.pull_request.number || github.ref }}"
            ),
            cancel_in_progress=True,
        ),
        env={"CACHIX_NAME": _CACHIX_NAME},
        permissions={"contents": "read"},
        jobs={
            "commitlint": _commitlint_job(),
            "quality": _quality_job(),
            "lint-pins-pinact": _lint_pins_pinact_job(),
            "verify-crate2nix": _verify_crate2nix_job(),
        },
    )


# ---------------------------------------------------------------------------
# Update certification workflow (.github/workflows/update-certify.yml)
# ---------------------------------------------------------------------------

_SELECT_REF_EXISTS = "needs.select-ref.outputs.exists == 'true'"


def _heavy_entry(
    package: str, *, fod_package: str | None = None
) -> dict[str, ScalarValue]:
    """Build one Darwin heavy-target matrix entry."""
    entry: dict[str, ScalarValue] = {
        "package": package,
        "target": f".#pkgs.aarch64-darwin.{package}",
    }
    if fod_package is not None:
        entry["fod_package"] = fod_package
    return entry


DARWIN_PRIORITY_HEAVY_ENTRIES = (
    _heavy_entry("codex-v8-native"),
    _heavy_entry("goose-cli-v8-native"),
    _heavy_entry("zed-editor-nightly"),
    _heavy_entry("opencode"),
    _heavy_entry("opencode-desktop-dev", fod_package="opencode-desktop"),
    _heavy_entry("codex"),
    _heavy_entry("gemini-cli"),
    _heavy_entry("element-desktop"),
    _heavy_entry("linear-cli"),
    _heavy_entry("neovide"),
)
DARWIN_EXTRA_HEAVY_ENTRIES = (
    _heavy_entry("goose-cli"),
    _heavy_entry("gitbutler"),
    _heavy_entry("superset"),
    _heavy_entry("scratch"),
    _heavy_entry("czkawka"),
    _heavy_entry("lumen"),
    _heavy_entry("mountpoint-s3"),
    _heavy_entry("mux"),
    _heavy_entry("rust-analyzer-unwrapped"),
)


def _certify_checkout_step() -> Step:
    """Check out the resolved update branch."""
    return _checkout_step(ref="${{ needs.select-ref.outputs.ref }}")


def _certify_shared_steps() -> tuple[Step, ...]:
    """Build the shared certification job preamble."""
    return (
        _certify_checkout_step(),
        _setup_nix_step(),
        _cachix_step(comment_lines=()),
        _nix_cache_step(
            key=_hash_files_key(_CERTIFY_HASH_FILES),
            comment_lines=(),
        ),
    )


def _select_ref_job() -> Job:
    """Resolve and gate the certification ref."""
    return Job(
        runs_on="ubuntu-24.04",
        outputs={
            "ref": "${{ steps.resolve.outputs.ref }}",
            "exists": "${{ steps.resolve.outputs.exists }}",
        },
        steps=(
            Step(
                name="Resolve certification ref",
                id="resolve",
                env={
                    "GITHUB_TOKEN": _UPDATE_TOKEN,
                    "TARGET_REF": (
                        "${{ github.event_name == 'workflow_dispatch' && "
                        "inputs.ref || env.UPDATE_BRANCH }}"
                    ),
                    "WORKFLOW_RUN_CONCLUSION": (
                        "${{ github.event.workflow_run.conclusion || '' }}"
                    ),
                    "WORKFLOW_RUN_HEAD_SHA": (
                        "${{ github.event.workflow_run.head_sha || '' }}"
                    ),
                },
                run=_lines(
                    'ref="${TARGET_REF}"',
                    'echo "ref=$ref" >> "$GITHUB_OUTPUT"',
                    'if [ "${GITHUB_EVENT_NAME}" = "workflow_run" ] && \\',
                    '  [ "${WORKFLOW_RUN_CONCLUSION}" != "success" ]; then',
                    "  echo \\",
                    '    "Refresh workflow concluded with '
                    "'${WORKFLOW_RUN_CONCLUSION}';\" \\",
                    "    \"checking '${ref}' for partial certification.\" \\",
                    "    >&2",
                    "fi",
                    'repo_url="https://x-access-token:${GITHUB_TOKEN}'
                    '@github.com/${GITHUB_REPOSITORY}.git"',
                    'if ! git ls-remote --exit-code --heads "$repo_url" '
                    '"refs/heads/$ref" >/dev/null 2>&1; then',
                    '  echo "exists=false" >> "$GITHUB_OUTPUT"',
                    "  echo \"No update branch '$ref' found; skipping "
                    'certification." >&2',
                    "  exit 0",
                    "fi",
                    'if [ "${GITHUB_EVENT_NAME}" = "workflow_run" ] && \\',
                    '  [ -n "${WORKFLOW_RUN_HEAD_SHA}" ]; then',
                    '  tmp_dir="$(mktemp -d)"',
                    "  trap 'rm -rf \"$tmp_dir\"' EXIT",
                    '  git init -q "$tmp_dir"',
                    '  git -C "$tmp_dir" fetch --no-tags --filter=blob:none '
                    '"$repo_url" \\',
                    '    "+refs/heads/$ref:refs/remotes/origin/$ref"',
                    '  if ! git -C "$tmp_dir" cat-file -e '
                    '"${WORKFLOW_RUN_HEAD_SHA}^{commit}" 2>/dev/null || \\',
                    '    ! git -C "$tmp_dir" merge-base --is-ancestor \\',
                    '      "${WORKFLOW_RUN_HEAD_SHA}" "refs/remotes/origin/$ref"; then',
                    '    echo "exists=false" >> "$GITHUB_OUTPUT"',
                    "    echo \\",
                    "      \"Update branch '$ref' does not contain "
                    'workflow_run head" \\',
                    "      \"'${WORKFLOW_RUN_HEAD_SHA}'; skipping stale "
                    'certification." \\',
                    "      >&2",
                    "    exit 0",
                    "  fi",
                    "fi",
                    'echo "exists=true" >> "$GITHUB_OUTPUT"',
                ),
            ),
        ),
    )


def _quality_gates_job() -> Job:
    """Run the shared quality gates against the update branch."""
    return Job(
        needs=("select-ref",),
        if_=_SELECT_REF_EXISTS,
        runs_on="ubuntu-24.04",
        timeout_minutes=60,
        steps=(
            *_certify_shared_steps(),
            Step(
                name="Run shared fast quality checks",
                run=_nix_check_builds(FAST_QUALITY_CHECKS),
            ),
            Step(
                name="Verify pinned action annotations with pinact",
                env={"GITHUB_TOKEN": _UPDATE_TOKEN},
                run="nix run --inputs-from . nixpkgs#pinact -- run --check",
            ),
            Step(
                name="Run shared deep verification checks",
                run=_nix_check_builds(DEEP_QUALITY_CHECKS),
            ),
            Step(
                name="Verify crate2nix artifacts are fresh",
                run="nix run .#nixcfg -- ci pipeline crate2nix",
            ),
        ),
    )


def _darwin_full_smoke_job() -> Job:
    """Dry-run full Darwin outputs on the update branch."""
    return Job(
        needs=("select-ref",),
        if_=_SELECT_REF_EXISTS,
        runs_on="macos-15",
        timeout_minutes=30,
        steps=(
            *_certify_shared_steps(),
            _prefetch_flake_inputs_step(),
            Step(
                name="Dry-run full Darwin outputs",
                run="nix run .#nixcfg -- ci workflow darwin eval-full-smoke",
            ),
        ),
    )


def _warm_fod_step(*, label: str) -> Step:
    """Build one FOD cache warm-up step."""
    return Step(
        name=f"Warm dependency cache for {label}",
        run="nix run .#nixcfg -- ci cache fod",
    )


def _warm_fod_cache_darwin_job() -> Job:
    """Warm the Darwin FOD cache after the full smoke run."""
    return Job(
        needs=("select-ref", "darwin-full-smoke"),
        if_=_SELECT_REF_EXISTS,
        runs_on="macos-15",
        timeout_minutes=180,
        steps=(
            *_certify_shared_steps(),
            _free_disk_space_step(),
            _warm_fod_step(label="aarch64-darwin"),
        ),
    )


def _warm_fod_cache_x86_64_linux_job() -> Job:
    """Warm the x86_64-linux FOD cache."""
    return Job(
        needs=("select-ref",),
        if_=_SELECT_REF_EXISTS,
        runs_on="ubuntu-24.04",
        timeout_minutes=180,
        steps=(
            *_certify_shared_steps(),
            _warm_fod_step(label="x86_64-linux"),
        ),
    )


def _warm_fod_cache_aarch64_linux_job() -> Job:
    """Warm the aarch64-linux FOD cache via a tarball checkout."""
    return Job(
        needs=("select-ref",),
        if_=_SELECT_REF_EXISTS,
        runs_on="ubuntu-24.04-arm",
        timeout_minutes=180,
        steps=(
            _tarball_checkout_step(
                step_name="Check out update branch archive",
                ref_expression="${CHECKOUT_REF}",
                env={
                    "CHECKOUT_REF": "${{ needs.select-ref.outputs.ref }}",
                    "GITHUB_TOKEN": _UPDATE_TOKEN,
                },
            ),
            _setup_nix_step(),
            _cachix_step(comment_lines=()),
            _nix_cache_step(
                key=_hash_files_key(_CERTIFY_HASH_FILES),
                comment_lines=(),
            ),
            _warm_fod_step(label="aarch64-linux"),
        ),
    )


def _darwin_heavy_job(
    *,
    entries: tuple[dict[str, ScalarValue], ...],
    warm_run: str,
    build_label: str,
) -> Job:
    """Build one sliced Darwin heavy-target build job."""
    return Job(
        needs=("select-ref", "darwin-full-smoke"),
        if_=_SELECT_REF_EXISTS,
        runs_on="macos-15",
        name="${{ matrix.package }}",
        timeout_minutes=240,
        strategy=Strategy(
            fail_fast=False,
            max_parallel=8,
            matrix=Matrix(include=entries),
        ),
        steps=(
            *_certify_shared_steps(),
            _free_disk_space_step(),
            _prefetch_flake_inputs_step(),
            Step(
                name="Warm dependency cache for ${{ matrix.package }}",
                run=warm_run,
            ),
            Step(
                name=f"Build {build_label} (${{{{ matrix.package }}}})",
                run="nix build --impure ${{ matrix.target }}",
            ),
        ),
    )


def _darwin_shared_job() -> Job:
    """Build the shared Darwin closure minus sliced heavy targets."""
    heavy_targets = tuple(
        str(entry["target"])
        for entry in (*DARWIN_PRIORITY_HEAVY_ENTRIES, *DARWIN_EXTRA_HEAVY_ENTRIES)
    )
    return Job(
        needs=("select-ref", "darwin-full-smoke"),
        if_=_SELECT_REF_EXISTS,
        runs_on="macos-15",
        timeout_minutes=180,
        steps=(
            *_certify_shared_steps(),
            _free_disk_space_step(),
            _prefetch_flake_inputs_step(),
            Step(
                name="Warm shared Darwin dependency cache",
                run="nix run .#nixcfg -- ci cache fod",
            ),
            Step(
                name="Build shared Darwin closure",
                run=_lines(
                    "nix run .#nixcfg -- ci cache closure \\",
                    "  --mode intersection \\",
                    *(f"  --exclude-ref {target} \\" for target in heavy_targets),
                    "  .#darwinConfigurations.argus.system \\",
                    "  .#darwinConfigurations.rocinante.system",
                ),
            ),
        ),
    )


def _darwin_host_job(*, host: str) -> Job:
    """Build one full Darwin host configuration."""
    return Job(
        needs=("select-ref", "darwin-priority-heavy", "darwin-shared"),
        if_=_SELECT_REF_EXISTS,
        runs_on="macos-15",
        timeout_minutes=240,
        steps=(
            *_certify_shared_steps(),
            _free_disk_space_step(),
            Step(
                name="Install tools required only for full Darwin host builds",
                run="nix run .#nixcfg -- ci workflow install-darwin-tools",
            ),
            _prefetch_flake_inputs_step(),
            Step(run=f"nix run .#nixcfg -- ci workflow build-darwin-config {host}"),
        ),
    )


def _linux_x86_64_job() -> Job:
    """Build the representative Linux output."""
    return Job(
        needs=("select-ref",),
        if_=_SELECT_REF_EXISTS,
        runs_on="ubuntu-24.04",
        timeout_minutes=30,
        steps=(
            *_certify_shared_steps(),
            Step(
                name="Warm dependency cache for nixcfg",
                run="nix run .#nixcfg -- ci cache fod --package nixcfg",
            ),
            Step(
                name="Build representative Linux output",
                run="nix build .#pkgs.x86_64-linux.nixcfg",
            ),
            Step(
                name="List update targets",
                run="nix run .#nixcfg -- ci workflow list-update-targets",
            ),
        ),
    )


def _publish_pr_certification_job() -> Job:
    """Publish certification results onto the open update PR."""
    return Job(
        needs=(
            "select-ref",
            "quality-gates",
            "darwin-priority-heavy",
            "darwin-extra-heavy",
            "darwin-shared",
            "darwin-argus",
            "darwin-rocinante",
            "linux-x86_64",
        ),
        if_=f"always() && !cancelled() && {_SELECT_REF_EXISTS}",
        runs_on="ubuntu-24.04",
        timeout_minutes=20,
        permissions={
            "actions": "read",
            "contents": "read",
            "pull-requests": "write",
        },
        steps=(
            *_certify_shared_steps(),
            Step(
                name="Resolve update PR",
                id="pr",
                env={
                    "GH_TOKEN": _UPDATE_TOKEN,
                    "PR_HEAD_REF": (
                        "${{ github.repository_owner }}:"
                        "${{ needs.select-ref.outputs.ref }}"
                    ),
                },
                run=_lines(
                    'pr_number="$(gh pr list \\',
                    '  --repo "${GITHUB_REPOSITORY}" \\',
                    '  --head "${PR_HEAD_REF}" \\',
                    "  --state open \\",
                    "  --json number \\",
                    '  --jq \'.[0].number // ""\')"',
                    'if [ -z "${pr_number}" ]; then',
                    '  echo "found=false" >> "$GITHUB_OUTPUT"',
                    "  echo \"No open PR found for ref '${PR_HEAD_REF}'; "
                    'skipping update." >&2',
                    "  exit 0",
                    "fi",
                    'echo "found=true" >> "$GITHUB_OUTPUT"',
                    'echo "number=${pr_number}" >> "$GITHUB_OUTPUT"',
                ),
            ),
            Step(
                name="Capture current PR body",
                if_="steps.pr.outputs.found == 'true'",
                env={"GH_TOKEN": _UPDATE_TOKEN},
                run=(
                    'gh pr view "${{ steps.pr.outputs.number }}" '
                    '--repo "${{ github.repository }}" --json body '
                    "--template '{{.body}}' > /tmp/pr-body-current.md"
                ),
            ),
            Step(
                name="Capture certification workflow run metadata",
                if_="steps.pr.outputs.found == 'true'",
                env={"GH_TOKEN": _UPDATE_TOKEN},
                run=(
                    "gh api repos/${{ github.repository }}/actions/runs/"
                    "${{ github.run_id }} > /tmp/certification-run.json"
                ),
            ),
            Step(
                name="Capture certification job results",
                if_="steps.pr.outputs.found == 'true'",
                env={"GH_TOKEN": _UPDATE_TOKEN},
                run=(
                    'gh api "repos/${{ github.repository }}/actions/runs/'
                    '${{ github.run_id }}/jobs?per_page=100" '
                    "> /tmp/certification-jobs.json"
                ),
            ),
            Step(
                name="Render updated PR body",
                if_="steps.pr.outputs.found == 'true'",
                run=(
                    "nix run .#nixcfg -- ci workflow "
                    "render-certification-pr-body "
                    "--existing-body /tmp/pr-body-current.md "
                    "--output /tmp/pr-body-updated.md "
                    "--run-json /tmp/certification-run.json "
                    "--jobs-json /tmp/certification-jobs.json "
                    '--cachix-name "${{ env.CACHIX_NAME }}"'
                ),
            ),
            Step(
                name="Update PR body with certification details",
                if_="steps.pr.outputs.found == 'true'",
                env={"GH_TOKEN": _UPDATE_TOKEN},
                run=(
                    'gh pr edit "${{ steps.pr.outputs.number }}" '
                    '--repo "${{ github.repository }}" '
                    "--body-file /tmp/pr-body-updated.md"
                ),
            ),
        ),
    )


def update_certify_workflow() -> Workflow:
    """Build the update certification workflow."""
    return Workflow(
        name="Update: Certify",
        env={
            "CACHIX_NAME": _CACHIX_NAME,
            "UPDATE_BRANCH": "update_flake_lock_action",
        },
        triggers=Triggers(
            comment_lines=(_TRIGGERS_DISABLED_COMMENT,),
            workflow_call=WorkflowCallTrigger(
                inputs={
                    "ref": WorkflowCallInput(
                        description=(
                            "Branch to certify. Defaults to the update branch "
                            "from the refresh workflow."
                        ),
                        required=False,
                        default="update_flake_lock_action",
                        type="string",
                    ),
                },
            ),
        ),
        concurrency=Concurrency(
            group="flake-update-certify",
            cancel_in_progress=False,
        ),
        permissions={"contents": "read"},
        jobs={
            "select-ref": _select_ref_job(),
            "quality-gates": _quality_gates_job(),
            "darwin-full-smoke": _darwin_full_smoke_job(),
            "warm-fod-cache-darwin": _warm_fod_cache_darwin_job(),
            "warm-fod-cache-x86_64-linux": _warm_fod_cache_x86_64_linux_job(),
            "warm-fod-cache-aarch64-linux": _warm_fod_cache_aarch64_linux_job(),
            "darwin-priority-heavy": _darwin_heavy_job(
                entries=DARWIN_PRIORITY_HEAVY_ENTRIES,
                warm_run=(
                    "nix run .#nixcfg -- ci cache fod "
                    '--package "${{ matrix.fod_package || matrix.package }}"'
                ),
                build_label="heavy target",
            ),
            "darwin-extra-heavy": _darwin_heavy_job(
                entries=DARWIN_EXTRA_HEAVY_ENTRIES,
                warm_run=(
                    'nix run .#nixcfg -- ci cache fod --package "${{ matrix.package }}"'
                ),
                build_label="extra heavy target",
            ),
            "darwin-shared": _darwin_shared_job(),
            "darwin-argus": _darwin_host_job(host="argus"),
            "darwin-rocinante": _darwin_host_job(host="rocinante"),
            "linux-x86_64": _linux_x86_64_job(),
            "publish-pr-certification": _publish_pr_certification_job(),
        },
    )


# ---------------------------------------------------------------------------
# Generated file inventory
# ---------------------------------------------------------------------------

GENERATED_WORKFLOWS = {
    UPDATE_WORKFLOW_PATH: update_workflow,
    CI_WORKFLOW_PATH: ci_workflow,
    UPDATE_CERTIFY_WORKFLOW_PATH: update_certify_workflow,
}


def render_generated_workflows() -> dict[str, str]:
    """Render every generated workflow document keyed by repo-relative path."""
    return {
        path: builder().render(header_comments=GENERATED_WORKFLOW_HEADER_COMMENTS)
        for path, builder in GENERATED_WORKFLOWS.items()
    }


__all__ = [
    "CI_WORKFLOW_PATH",
    "DARWIN_EXTRA_HEAVY_ENTRIES",
    "DARWIN_PRIORITY_HEAVY_ENTRIES",
    "DEEP_QUALITY_CHECKS",
    "FAST_QUALITY_CHECKS",
    "GENERATED_WORKFLOWS",
    "GENERATED_WORKFLOW_HEADER_COMMENTS",
    "UPDATE_CERTIFY_WORKFLOW_PATH",
    "UPDATE_WORKFLOW_PATH",
    "ci_workflow",
    "render_generated_workflows",
    "update_certify_workflow",
    "update_workflow",
]
