"""Normalize generated crate2nix output for the checked-in Codex Cargo.nix."""

from lib.cargo_nix_normalizer import normalize as normalize_cargo_nix

_LOCAL_PATH_PREFIXES = (
    "agent-identity",
    "analytics",
    "ansi-escape",
    "app-server",
    "app-server-client",
    "app-server-protocol",
    "app-server-test-client",
    "apply-patch",
    "arg0",
    "artifacts",
    "async-utils",
    "aws-auth",
    "backend-client",
    "chatgpt",
    "cli",
    "cloud-requirements",
    "cloud-tasks",
    "cloud-tasks-client",
    "cloud-tasks-mock-client",
    "codex-api",
    "codex-backend-openapi-models",
    "codex-client",
    "codex-experimental-api-macros",
    "codex-mcp",
    "code-mode",
    "collaboration-mode-templates",
    "config",
    "connectors",
    "core",
    "core-plugins",
    "core-skills",
    "debug-client",
    "device-key",
    "exec",
    "exec-server",
    "execpolicy",
    "execpolicy-legacy",
    "feedback",
    "features",
    "file-search",
    "git-utils",
    "hooks",
    "install-context",
    "instructions",
    "keyring-store",
    "linux-sandbox",
    "lmstudio",
    "login",
    "mcp-server",
    "model-provider",
    "model-provider-info",
    "models-manager",
    "network-proxy",
    "ollama",
    "otel",
    "package-manager",
    "plugin",
    "process-hardening",
    "protocol",
    "realtime-webrtc",
    "responses-api-proxy",
    "response-debug-context",
    "rmcp-client",
    "rollout",
    "rollout-trace",
    "sandboxing",
    "secrets",
    "shell-command",
    "shell-escalation",
    "skills",
    "state",
    "stdio-to-uds",
    "terminal-detection",
    "test-binary-support",
    "thread-store",
    "tools",
    "test-macros",
    "tui",
    "uds",
    "utils",
    "v8-poc",
    "windows-sandbox-rs",
)


def normalize(text: str) -> tuple[str, int, bool]:
    """Return normalized Codex Cargo.nix text plus replacement counts."""
    return normalize_cargo_nix(
        text,
        local_path_prefixes=_LOCAL_PATH_PREFIXES,
    )
